# Cache docker images
cache:
  key: one-key-to-rule-them-all

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: normal


antora-build:
  stage: build
  tags:
    - asciidoc
  image:
    name: ggrossetie/antora-lunr
    entrypoint: [""]
  script:
    - antora --stacktrace site.yml
  # artifacts:
  #   paths:
  #     - site