version: "2"

services:

  antora:
    image: ghcr.io/asam-ev/project-guide-docker:3
    volumes:
      - .:/usr/src/app/repo #has to match WORKSPACE defined in Dockerfile + folder from package.json "docker-build"
    depends_on:
      - kroki
    entrypoint: npm run docker-build
    # entrypoint: /bin/bash


  kroki:
    image: yuzutech/kroki:0.15.1
    environment:
      - KROKI_MAX_URI_LENGTH=20000
    