version: "2"

services:

  custom-lunr:
    build:
      context: doc\modules\compendium\assets\attachments\.
      dockerfile: DOCKERFILE.custom
    volumes:
      - .:/antora
    # entrypoint:  --stacktrace antora-playbook.yml
    # entrypoint: sh
    command: --stacktrace site.yml