version: "2"

services:

  antora:
    image: ghcr.io/asam-ev/project-guide-docker:sha-e899eb5
    volumes:
      - .:/usr/src/app/osc2 #has to match WORKSPACE defined in Dockerfile + folder "osc2" from package.json-> docker-build
    depends_on:
      - kroki
    entrypoint: npm run docker-build
    # entrypoint: /bin/bash


  kroki:
    image: yuzutech/kroki
    environment:
      - KROKI_MAX_URI_LENGTH=20000
    