version: "2"

services:
  asciidoctor:
    image: asciidoctor/docker-asciidoctor
    volumes:
      - .:/documents
    entrypoint: asciidoctor -r asciidoctor-diagram -a mathjax --trace '**/*.adoc'

# run with docker-compose run antora
  antora:
    image: antora/antora
    volumes:
      - .:/antora
    # entrypoint:  --stacktrace antora-playbook.yml
    # entrypoint: sh
    command: --stacktrace site.yml


