= ASAM Project Guide - Generator

image::https://github.com/asam-ev/asam-project-guide/actions/workflows/site-build.yml/badge.svg?branch=main[link=https://github.com/asam-ev/asam-project-guide/actions/workflows/site-build.yml]

****
IMPORTANT: This repository contains the generator and general setup for Antora in context of the Project Guide.
It does not contain the content itself!
This can be found https://github.com/asam-ev/asam-project-guide-content[here] instead.
****

Hosted version available at:
https://asam-ev.github.io/asam-project-guide[ASAM Project Guide (Link)]


== Building locally
To build the Project Guide locally, check out this repository.
Next, check out the https://github.com/asam-ev/asam-project-guide-content[content repository^] to a new subfolder (e.g. "contents").
In order for the generator to use the local sources, edit the 'site.yml' so that each `url` attribute under `content`/`sources` points to that folder (e.g. `./contents`). +
If you also want to include specific branches and/or tags (or exclude them), change the other settings accordingly.
For more information on how the 'site.yml' works, see https://docs.antora.org/antora/latest/playbook/set-up-playbook/[the official Antora documentation].