= ASAM Project Guide

image::https://github.com/asam-ev/asam-project-guide/actions/workflows/site-build.yml/badge.svg?branch=main[link=https://github.com/asam-ev/asam-project-guide/actions/workflows/site-build.yml]

****
IMPORTANT: This guide is a work in progress and subject to change!
****

Hosted version available at:
https://asam-ev.github.io/asam-project-guide/asamprojectguide/baseline/home.html[ASAM Project Guide (Link)]

---
Includes: Standard template, manuals, guidelines, build + test, resources.
All standard are written after one version of the ASAM proect guide.

---



== Chapter structure draft

. Introduction
. Overview

// WG Member
. ASAM general process of a project (ASAM Project Handbook, wiki)
.. General standard development
.. Working Model (workgroups)
.. Issue-driven workflow
.. Review, Release
. Deliverables of ASAM standards (standard documentation, user guide, UML model, examples, what shall not be included (e.g. implementation, tool))

. Standard Tools
.. VSCode
.. GitLab
.. git
.. local build asciidoctor


// Project Lead
. Project Lead Guide

// Technical Writer
. Editorial Guide (Redaktionleitfaden)
.. Asciidoc syntax reference/conventions
.. Writing Rules, Spelling
.. Checklist for technical writer
.. Document types
... Document structure
... Fragment types
.. Terminology concept


// ASAM Office
. Handling repos
. Pipeline internals
. Release Process & Tagging & gitattributes
. GitLab Workflow and Branching


Standard Template

---

include::./doc/modules/ROOT/pages/antora/Build-Antora-Locally.adoc[leveloffset=+1]

---