site:
  title: ASAM Project Guide
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://asam-ev.github.io/asam-project-guide/
  start_page: latest@asamprojectguide::index.adoc

content:
  sources:
    - url: https://github.com/asam-ev/asam-project-guide-content.git
    # - url: ./asam-project-guide-content
      # branches: HEAD,baseline_*,open*
      branches: main, pre-restructuring
      tags: open*, v*
      start_path: content
      edit_url: 'https://github.com/asam-ev/asam-project-guide-content/blob/{refname}/{path}'
    - url: https://github.com/asam-ev/asam-project-guide-content.git
    # - url: ./asam-project-guide-content
      branches: main
      tags: v*
      start_path: guide
      edit_url: 'https://github.com/asam-ev/asam-project-guide-content/blob/{refname}/{path}'

ui:
  bundle:
    # url: ./ui-bundle.zip
    url: https://code.asam.net/common/style-resources/-/raw/master/antora/ui-bundle.zip?inline=false
    snapshot: true
  supplemental_files: ./supplemental_ui

output:
  clean: true
  dir: ./site

runtime:
  fetch: true

# tag::asciidoctor[]
asciidoc:
  attributes:
    page-pagination: true
    guide-repo-url: https://github.com/asam-ev/asam-project-guide/
    hide-uri-scheme:
    gitlab-url: https://code.asam.net
    kroki-server-url: 'http://kroki:8000'
    kroki-fetch-diagram: ""
    abb: asamprojectguide:compendium:partial$abbreviations.adoc
    # Allow URI read to retrieve SVG on compilation
    allow-uri-read: true
    # use SVG unless otherwise specified
    kroki-default-format: svg
    # Make SVG inline so that we can get interactive actions (can be overridden by schema with "opts=none")
    kroki-default-options: interactive
    credits: 'xref:ROOT:credits.adoc[]'
    # Configuration for feedback button. The button is defined in the header-content.hbs in ./supplemental_ui/partials
    page-feedbackurl: https://github.com/asam-ev/asam-project-guide/issues/new
    page-feedbacktype: github


    # tag::roles[]
    ## Defined role attributes
    role-reviewer: 'xref:role-specific:reviewer.adoc[<role style="background:#FA8072;" >REVIEWER</role>]'
    role-wg-member: 'xref:role-specific:wg-member.adoc[<role style="background:#BDB76B;" >WG MEMBER</role>]'
    role-wg-lead: 'xref:role-specific:wg-lead.adoc[<role style="background:#14BCCD;" >WG LEAD</role>]'
    role-technical-writer: 'xref:role-specific:technical-writer.adoc[<role style="background:#D8BFD8;" >TECHNICAL WRITER</role>]'
    role-project-lead: 'xref:role-specific:project-lead.adoc[<role style="background:#6A5ACD;" >PROJECT LEAD</role>]'
    role-gtm: 'xref:role-specific:gtm.adoc[<role style="background:#32CD32;" >GTM</role>]'
    role-service-provider: 'xref:role-specific:service-provider.adoc[<role style="background:#FFDEAD;" >SERVICE PROVIDER</role>]'
    role-standard-user: 'xref:role-specific:standard_user.adoc[<role style="background:#CD853F;" >STANDARD USER</role>]'
    role-standard-manager: 'xref:role-specific:standard_manager.adoc[<role style="background:#DEB887;" >STANDARD MANAGER</role>]'
    role-idea-giver: '<role style="background:LightGray;">Idea Giver</role>'
    role-tsc-member: '<role style="background:LightGray;">TSC Member</role>'
    role-member: '<role style="background:LightGray;">ASAM Member</role>'
    role-proposal-submitter: '<role style="background:LightGray;">Proposal Submitter</role>'
    # end::roles[]

    ## Labels
    mandatory: '<label class="mandatory"/>'
    recommended: '<label class="recommended"/>'
    optional: '<label class="optional"/>'

  extensions:
  - asciidoctor-kroki
  - '@djencks/asciidoctor-mathjax'
  - './antora_extensions/tabs-block/extension.js'
#   - asciidoctor-diagram

# end::asciidoctor[]


# tag::antora[]
antora:
  extensions:
    - require: '@antora/antora-lunr-extension'
    - require: './antora_extensions/asam-extension.js'
      keywords:
        filename: "1_keywords.adoc"
        module: "compendium"
        createOverview: true
      add_to_navigation: true
      unlisted_pages_heading: Orphans
  # end::antora[]