site:
  title: ASAM Project Guide
  # the 404 page and sitemap files only get generated when the url property is set
  # TODO: This has to be changed to the actual hosting
  url: https://code.asam.net/common/asam-project-guide
  start_page: asamprojectguide::home.adoc
content:
  sources:
    - url: .
      branches: HEAD
      tags: open*
      start_path: doc


# ui:
#   bundle:
#     url: ./antora_ui_bundle/bundled/ui-bundle.zip
#     snapshot: true
#   supplemental_files: /usr/local/share/.config/yarn/global/node_modules/antora-lunr/supplemental_ui

  ui:
  bundle:
    url: ./ui-bundle.zip
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental_ui

output:
  clean: true
  dir: ./site

asciidoc:
  attributes:
    plantuml-server-url: http://www.plantuml.com/plantuml
    guide-repo-url: https://code.asam.net/common/asam-project-guide/
    hide-uri-scheme:
    gitlab-url: https://code.asam.net
    # diagram-max-get-size: 8192
    # Defined role attributes
    role-reviewer: 'xref:role-specific:reviewer.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#FA8072;" >REVIEWER</role>]'
    role-wg-member: 'xref:role-specific:wg-member.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#BDB76B;" >WG MEMBER</role>]'
    role-technical-writer: 'xref:role-specific:technical-writer.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#D8BFD8;" >TECHNICAL WRITER</role>]'
    role-project-lead: 'xref:role-specific:project-lead.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#6A5ACD;" >PROJECT LEAD</role>]'
    role-gtm: 'xref:role-specific:gtm.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#32CD32;" >GTM</role>]'
    role-service-provider: 'xref:role-specific:service-provider.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#FFDEAD;" >SERVICE PROVIDER</role>]'
    role-standard-user: 'xref:role-specific:standard-user.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#CD853F;" >STANDARD USER</role>]'
    role-standard-manager: 'xref:role-specific:standard-manager.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#DEB887;" >STANDARD MANAGER</role>]'


  extensions:
  - asciidoctor-kroki
#   - asciidoctor-diagram