site:
  title: ASAM Project Guide
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://asam-ev.github.io/asam-project-guide/
  start_page: master@asamprojectguide::index.adoc

content:
  sources:
    - url: .
      # branches: HEAD,baseline_*,open*
      branches: HEAD
      tags: open*
      start_path: doc
      edit_url: 'https://github.com/asam-ev/asam-project-guide/blob/{refname}/{path}'


# ui:
#   bundle:
#     url: ./antora_ui_bundle/bundled/ui-bundle.zip
#     snapshot: true
#   supplemental_files: /usr/local/share/.config/yarn/global/node_modules/antora-lunr/supplemental_ui

ui:
  bundle:
    url: ./ui-bundle.zip
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental_ui

output:
  clean: true
  dir: ./site

runtime:
  fetch: true

asciidoc:
  attributes:
    page-pagination: true
    guide-repo-url: https://github.com/asam-ev/asam-project-guide/
    hide-uri-scheme:
    gitlab-url: https://code.asam.net
    kroki-server-url: 'http://kroki:8000'
    kroki-fetch-diagram: ""
    abb: compendium:partial$abbreviations.adoc
    # Allow URI read to retrieve SVG on compilation
    allow-uri-read: true
    # use SVG unless otherwise specified
    kroki-default-format: svg
    # Make SVG inline so that we can get interactive (can be overridden by schema with "opts=none")
    kroki-default-options: interactive
    credits: 'xref:ROOT:credits.adoc[]'


    ## Defined role attributes
    role-reviewer: 'xref:role-specific:reviewer.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#FA8072;" >REVIEWER</role>]'
    role-wg-member: 'xref:role-specific:wg-member.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#BDB76B;" >WG MEMBER</role>]'
    role-wg-lead: 'xref:role-specific:wg-lead.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#14BCCD;" >WG LEAD</role>]'
    role-technical-writer: 'xref:role-specific:technical-writer.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#D8BFD8;" >TECHNICAL WRITER</role>]'
    role-project-lead: 'xref:role-specific:project-lead.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#6A5ACD;" >PROJECT LEAD</role>]'
    role-gtm: 'xref:role-specific:gtm.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#32CD32;" >GTM</role>]'
    role-service-provider: 'xref:role-specific:service-provider.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#FFDEAD;" >SERVICE PROVIDER</role>]'
    role-standard-user: 'xref:role-specific:standard_user.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#CD853F;" >STANDARD USER</role>]'
    role-standard-manager: 'xref:role-specific:standard_manager.adoc[<role style="color:black;font-weight: bold;width:500px;height:100px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#DEB887;" >STANDARD MANAGER</role>]'

    ## Labels
    mandatory: '<label style="color:black;font-weight: bold;width:140px;height:40px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#CA4444;" >MANDATORY</label>'
    recommended: '<label style="color:black;font-weight: bold;width:140px;height:40px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#E69138;" >RECOMMENDED</label>'
    optional: '<label style="color:black;font-weight: bold;width:140px;height:40px;border-radius: 25px;margin:10px 2px;padding:5px 15px;border:2px solid #000;background:#76A5AF;" >OPTIONAL</label>'

  extensions:
  - asciidoctor-kroki
  - '@djencks/asciidoctor-mathjax'
#   - asciidoctor-diagram

antora:
  extensions:
    - require: '@antora/antora-lunr-extension'
    - require: './antora_extensions/asam-extension.js'
      keywords:
        filename: "1_keywords.adoc"
        module: "compendium"
        createOverview: true
      add_to_navigation: true
      unlisted_pages_heading: Orphans