= OSC2 Scenario Writing Process
:description: TODO
:keywords: TODO

include::compendium:partial$_attributes.adoc[]

. Select a scenario specification from the Extracted Scenario Specifications table on the Miro board

. Create an https://code.asam.net/simulation/standard/openscenario-2.0/-/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D=#[issue on the repository^] using the Scenario Feedback template (see the existing issues as a reference https://code.asam.net/simulation/standard/openscenario-2.0/-/issues?label_name%5B%5D=ScenarioDescription[here^])
** Issue Title: <Scenario ID> <Scenario Title>
** Description: <Scenario abstraction level>
** Due Date: When will you be able to deliver a first draft?

. Start writing the scenario using the https://code.asam.net/simulation/standard/openscenario-2.0/-/jobs/artifacts/master/raw/Language/ASAM_OpenSCENARIO_BS-1-6_Language-Reference-Manual_V2-0-0.html?job=draft[OpenSCENARI0 2.0 Language Reference Manual^]

. When you have a first draft of the scenario, commit it to the repository.
Make sure to stick to the directory structure defined below (creating folders if neccessary):

+
.Directory structure for scenario files
[caption=]
====
The three tables in the Miro Board are used to create a directory structure, with each table representing one hierarchy level:



[source,subs="+macros"]
....
icon:folder[] Examples
├─── icon:folder[] <Case study ID>_<Case Study Name>
|    └─── icon:folder[] <scenario specification ID>_<Scenario Specification Title>
|         └─── icon:folder[] <osc2 scenario ID>_<OpenSCENARIO 2.0 Scenario Title>
|              └─── icon:file[] OpenSCENARIO 2.0 Scenario files and supporting content
├─── icon:folder[] <Case study ID>_<Case Study Name>
└─── ...
....
====

. If you find you cannot represent something using the language, either because it is not defined or you are lacking the knowledge, describe it in plain text in the file.

** Flag other participants of the implementers forum for input to help detail out the sections you are struggling with (using @ followed by a username to flag someone)

** Scenario specification subgroup meetings will be used to review and discuss areas where you need support

** If the group agrees that the feature in question cannot be written,  members of the development project are approached for input/feedback.
In a comment, detail out all information the users need to understand the problem then flag the members using `@`.

You find a list of persons responsible for the different topics from the development project https://code.asam.net/simulation/standard/openscenario-2.0/-/wikis/Contact-Persons-from-OSC2-Development-Project[here^].
