= How to contribute to a proposal directly in AsciiDoc files
:description: Describes how one can participate in the creation of a proposal through directly entering content in the appropriate AsciiDoc files.
:keywords: proposal, asciidoc, READYFORREVIEW

include::compendium:partial$_attributes.adoc[]

//tag::roles[]
{role-wg-member}
{role-project-lead}
//end::roles[]

The most direct way of contributing to a project is by creating and editing the AsciiDoc files.
However, in order for a consistent workflow and optimal use of the automation steps set up by __{asam}__, users must first familiarize themselves with the instructions on <<The GitLab workflow,GitLab>> and <<Writing content in AsciiDoc,AsciiDoc>> and follow them.
This ensures that all projects work the same way and deliver the same high level of quality that is expected from an ASAM standard.

Each project proposal has the same base structure which is described and explained in the `README.adoc` file at root level of the repository.
Consider the correct document before adding new content to a file.

IMPORTANT: Do **not** edit the `main.adoc` file directly!
All content is included through the files in the folder `subchapters`.

== The GitLab workflow

The repository-based approach of ASAM for working on documents allows members to work in parallel on the same documents without the risk of overwriting each others changes without notice.

Users **must** follow the xref:compendium:guides/workflow_tutorial.adoc[].

== Writing content in AsciiDoc
include::compendium:partial$asciidoc.adoc[]

Users **must** follow these guidelines:
* xref:compendium:writing_guidelines/asciidoc_guide.adoc[]
* xref:compendium:writing_guidelines/writing_guide.adoc[]
* xref:compendium:writing_guidelines/editorial_guide.adoc[]