= Setting up microsoft teams and sharepoint
:description: Setup of MS Teams and sharepoint
:keywords: setup,teams,sharepoint,TODO

include::partial$_attributes.adoc[]
include::{abb}[]

{sharepoint-icon}
{teams-icon}

// If you use a recurring image for similar artifacts, declare it as attribute in partials/_attributes.adoc and reference here.

== Context
MS Teams and sharepoint are used at __{asam}__ to allow for communication (both through text and audio/video) within project teams and exchange files and documents without direct impact on the standardization processes.
In order to use these tools, an initial setup is required.

== Result
* User can access Microsoft Teams (assigned teams)
* User can access Sharepoint (shared folders)
* User can add and download files from Sharepoint

== Prerequisites
* Access to MS Teams and Sharepoint has been granted by ASAM.
* Full access: Microsoft 365 Business Standard, Microsoft 365 Enterprise, and Microsoft 365 Education license

WARNING: If you do not yet have access to Teams, get in touch with mailto:benjamin.engel@asam.net[Benjamin Engel].

== How
//Describe the steps to perform this artifact. If you have alternative ways, use subchapters.

== Troubleshooting / Known Issues
=== I do not have mS Teams


=== My ASAM Teams account cannot access any team channel
Check with your ASAM contact if you have already been assigned to any team or channel yet.
You will receive an email from `noreply@email.teams.microsoft.com` when your account has been added to at least one channel.

=== I cannot access my sharepoint folder
Try navigating to the parent folder and then access the target folder from there again.
If this does not work: Check with your ASAM contact if your access to the folder has been revoked or the folder has been renamed.

//OPTIONAL: Add the reference macro with keywords you want to reference.
// Example: related::guide,!main[]   <-- (lists all pages where the keyword "guide" but not "main" were used)

