graph TD
    A[Idea] --> B{New or existing standard?}
    B -->|New standard| C[Ideation workshop]
    C --> D
    B -->|Existing standard| D{Enough 3+ participants?}
    D -->|No| D
    D -->|Yes| E[Draft project proposal]

    C -.-> xC[/Basis for Proposal/]
    xC -.->E