graph TD
    start (()) --> J[Submit Proposal document to TSC]
    J --> K[Present Project Proposal at next TSC meeting]
    K --> L{Proposal approved?}
    L -->|No, small updates required| end_1 ((Finalize Proposal document))
    L -->|No, large updates required| end_2 ((Draft project proposal))
    L -->|Yes| M[Start project]

    xH[/Final Proposal/] -.-> J
    xH -.-> K