graph TD
    subgraph Initiation
    A[Idea] --> B{New or existing standard?}
    B -->|New standard| C[Ideation workshop]
    end
    C --> D
    subgraph Proposal drafting
    B -->|Existing standard| D{Enough 3+ participants?}
    D -->|No| D
    D -->|Yes| E[Draft project proposal]
    E --> F[Organize Proposal workshop]
    F --> G[Proposal workshop]
    G --> H[Finalize Proposal document]
    end
    subgraph Proposal decision
    H --> I[Select proposal submitter]
    I --> J[Submit Proposal document to TSC]
    J --> K[Present Project Proposal at next TSC meeting]
    K --> L{Proposal approved?}
    end
    L -->|No, small updates required| H
    L -->|No, large updates required| E
    L -->|Yes| M[Start project]

    C -.-> xC[/Basis for Proposal]
    xD[[Proposal template]] -.-> E
    xC -.->E
    E -.-> xE[/Proposal DRAFT/]
    xF[[Proposal workshop gameplan]] -.-> F
    xE -.-> G
    G -.-> xG[/Agreement on project scope/]
    xG -.-> H
    H -.-> xH[/Final Proposal/]
    xH -.-> J
    xH -.-> K