= Build Antora On Your Local PC
:description: Describes how to build antora locally on you pc without needing to run the CI/CD on GitLab.
:keywords: antora,guide,docker

This guide explains how to build this wiki locally on your PC without having activate the ASAM build pipeline.
The suggested method is to use the provided docker-compose.yml in this repository.

== Build With Custom Image (Pro)

NOTE: This service provides a searchbar in the header and support for diagrams.

. Check out the link:https://github.com/Mogztter/antora-lunr[antora-lunr repository]
. Create a new file namend "DOCKERFILE.custom" in the folder of that repository and add the following content to it:
+
[source,docker]
----
FROM ggrossetie/antora-lunr
RUN yarn global add asciidoctor-kroki
----
+
. Start docker (if not already open)
. Open a xref:../tool-specific/PowerShell-Basics.adoc[Powershell] in this folder
. Run the following command to create the custom image:
+
[source,docker]
----
docker build -t local/antora-lunr:latest -f Dockerfile.custom .
----
+
TIP: Alternatively, you can also download link:{attachmentsdir}/DOCKERFILE.custom[this example, opts="download", download="true"] and use it directly.
. Check out the latest version of this repository (containing the project guide)
. Build and run a docker container using the provided docker-compose.yml for the service "custom-lunr"

== Build With Antora/Lunr (Recommended)

NOTE: This service provides a searchbar in the header but no support for diagrams.

. Check out the latest version of this repository
. Start docker (if not yet running)
. Build and run a docker container using the provided docker-compose.yml for the service "lunr"

== Build With Antora
NOTE: This service does not provide a searchbar or support for diagrams.

. Check out the latest version of this repository
. Start docker (if not yet running)
. Build and run a docker container using the provided docker-compose.yml for the service "antora"

TIP: If you get an error message that ".../antora-lunr/supplemental_ui" was not found, use <<Build With Antora/Lunr (Recommended),Lunr>> instead.

