
:abb-link: xref:compendium:abbreviations.adoc#_

:api: {abb-link}api[API]
:asam: {abb-link}asam[ASAM]
:ccb: {abb-link}ccb[CCB]
:cr: {abb-link}cr[CR]
:dco: {abb-link}dco[DCO]
:gtm: {abb-link}gtm[GTM]
:tsc: {abb-link}tsc[TSC]
:vscode: {abb-link}vscode[VSCode]
:wg: {abb-link}wg[WG]

ifdef::is_abbreviations[]

== API
Application Programming Interface:: An application programming interface (API) is a connection between computers or between computer programs.
It is a type of software interface, offering a service to other pieces of software. See https://en.wikipedia.org/wiki/API[Wikipedia^].

== ASAM
Association for Standardization of Automation and Measuring Systems:: ASAM is a non-profit organization that promotes standardization for tool chains in automotive development and testing. See https://www.asam.net/about-asam/our-vision/[ASAM website^]

== CCB
Change Control Board:: TODO

== CR
Change Request:: TODO

== DCO
Developer Certificate of Origin:: The DCO is an attestation attached to every contribution made by every developer.

== GTM
ASAM Global Technology Manager:: A GTM is an ASAM employee focussed on coordinating project processes and the background work behind a project.

== TSC
Technical Steering Committee::
https://www.asam.net/active-projects/technical-steering/

== VSCode
Visual Studio Code:: xref:tooling:vscode.adoc[]

== WG
Workgroup:: A subgroup within a project dedicated to a specific topic.
Consists of xref:role-specific:wg-member.adoc[workgroup members] and a xref:role-specific:wg-lead.adoc[workgroup lead].

endif::[]