= Meeting guidelines
:description: TODO
:keywords: TODO

include::compendium:partial$_attributes.adoc[]

== Whom to invite?
- While the project is still in the early phase, people will likely be moving around in groups
- Send the invite to those emails registered for the group; additionally, CC the following:
  - The project lead and the ASAM representative.
  - The shared OpenX Calendar, openx@asam.net.
  - The Teams channel email; this will post the meeting in the channel for all to see.
  See xref:compendium:tools/teams/obtain_channel_email.adoc[].

> To find the list of people registered for your group or WP, see the WP signup list.
Its location is described in the xref:compendium:tools/teams/teams-channel_file-structure.adoc[Teams&Sharepoint Overview].

// TODO: find correct link and information supposed to go here.
// TODO: write the full meaning of "WP"

== Setting up a meeting
- If you have a Teams license, you can setup a Teams meeting directly.
See xref:compendium:tools/teams/meetings_in_teams.adoc[].
- Otherwise, feel free to use whatever solution you or your company normally use.
- If all else fails, send the details to your ASAM representative and they will assist (either Teams or Zoom).
