= Documentation processes

== GitLab issues

In ASAM projects GitLab is used to manage the standard development processes.
GitLab issues that are documentation related are created by project members and technical writers.
This section contains information on documentation related GitLab issues.

=== Live-cycles for GitLab issues

This section displays the GitLab issue live-cycles when crating documentation for ASAM and explains labels used in GitLab for specific live-cycles.

* Every documentation related GitLab issue shall have a `isDocumentationRelated` label.
* If a GitLab issue is ready for creating content for the documentation the project members assign the `isReadyForServiceProvider` label to the issue.
* If a technical writer starts working on the documentation the technical writer assigns the `isInProgress` label to the GitLab issue.
* If a technical writer has questions regarding a GitLab issue the technical writer assigns the `needsClarification` label to the issue.
* If a GitLab issue has been finally edited by a technical writer the technical writer assigns the `needsReview` label to the issue.
* All GitLab issues labeled `needsReview` will be discussed in the upcoming project meeting.
The technical writer presents the changes to the project members.
* If the changes are accepted by the project members the GitLab issue is closed.
* If there are objections regarding a change to the documentation a new iteration process starts.
Objections are communicated by the project members and added to the GitLab issue.

==== Labels for GitLab issues

[#tab-e328478e-6096-43a0-a4f6-4e622085da6a]
[%header, cols="3*"]
|===
|Status tag                |Description                                                                                                                          |Color code
|isDocumentationRelated    |Assign the `isDocumentationRelated` label to a GitLab issue when an issue contains tasks for technical writers.                      |#428BCA
|isInProgress              |Assign the `isInProgress` label to a GitLab issue when a technical writer starts working on an issue.                                |
|isReadyForServiceProvider |Assign the `isReadyForServiceProvider` label to a GitLab issue when the issue is ready so that a technical writer can start working. |
|needsClarification        |Assign the `needsClarification` label to a GitLab issue if a technical writer needs more information regarding an issue.             |
|needsReview               |Assign the `needsReview` label to a GitLab issue when a technical writer finished working on an issue.                              |
|===

== Editorial rules

In the ASAM Editorial Guide, editorial rules exist, project members and technical writers shall apply when crating documentation for ASAM.
This section contains information how to create and apply editorial rules.

=== Using editorial rules

. Provide the ASAM Editorial Guide to project members and technical writers when a project starts.
. Project members should try to apply the editorial rules.
. Technical writers may educate project members who do not apply the editorial rules.
. Technical writers shall review the content committed by project members as soon as possible.

=== Applying and creating rules

When creating documentation for ASAM the following approach is applicable:

. Check if an appropriate editorial rule exists in the ASAM Editorial Guide when creating documentation.
.. Apply the editorial rule to the documentation if a rule exists.
.. Create a new editorial rule if no rule exists.

Three tags can be assigned to editorial rules in the list of rules:

[#tab-d13e899d-e03a-424a-9dc1-c363211d49a1]
[%header, cols="2*"]
|===
|Status tag |Description
|draft      |The `draft` tag is assigned to editorial rules that have been created and are not approved yet.
|approved   |The `approved` tag is assigned to editorial rules the OpenX team agreed on and that shall be applied when crating documentation for ASAM.
|rejected   |The `rejected` tag is assigned to editorial rules the OpenX team did not agree on and that shall not be applied when crating documentation for ASAM.
|===

=== Creating new editorial rules

Start the process of creating new editorial rules when an error in the documentation becomes obvious, for example when sentences in lists sometimes end having a period and sometimes not.

=== Adding an editorial rule to rules.csv

The `rules.csv` file contains a list of all editorial rules.

* Create a rule number in `rules.csv` file if no rule exists.
* Mark the created editorial rule in the `rules.csv` file as `draft`.

*Example*

[source, csv]
----
Number,Short_Description,Link_to_Project_Guide,Link_to_Test,Status
ASM-1,No fixed versioning,-,-,draft
----

[#tab-db59ff67-f1e4-4e3f-a662-76699495a813]
[%header, cols="2*"]
|===
|Column                |Description
|Number                |Assign a new unique identifier following the convention `ASM-[number]`, for example `ASM-1`.
|Short_Description     |Add a short description that explains the subject of the editorial rule.
|Link_to_Project_Guide |Add a link to the section in the ASAM Editorial Guide that contains information on the editorial rule.
|Link_to_Test          |Add a link to the file that contains the automatic test.
|Status                |Assign the status for a new editorial rule, for example `draft`.
|===

=== Adding an editorial rule to the ASAM Editorial Guide

. Create a new section in the ASAM Editorial Guide.
. Brainstorm how to document the specific editorial rule.
. Have a look at existing resources, for example the Google developer documentation style guide.
.. Check if an editorial rule in the https://asd-ste100.org/request.html[ASD-STE100 Specification] (Simplified Technical English) exists.
.. Check if an editorial rule in the https://developers.google.com/style/[Google developer documentation style guide] and the https://docs.microsoft.com/en-us/style-guide/welcome/[Microsoft Writing Style Guide] exists.
. Extract useful editorial rules from the existing resources.
. Adjust the wording in editorial rules when transferring rules to the ASAM Editorial Guide, for example Microsoft names elements of a sentence item, that are named element at ASAM.
. Draft the section for the editorial rule in the ASAM Editorial Guide.
. Have a look if an automatic test exists, for example for vale.
. Add a link to the `rules.csv` file on the section for the editorial rule and the file for the automatic test if applicable.
