[#top-cf80501d-bcfb-4014-82b7-ee21314f52d9]
= Editorial guide
:description: Editorial guide for technical writers
:keywords: writing_guide
:numbered:

include::compendium:partial$_attributes.adoc[]
include::{abb}[]

{role-technical-writer}
{role-wg-member}


This section contains the ASAM Editorial Guide for technical writers and working group members.
It contains editorial rules for contributing content to a project in written form.

If an editorial rule is missing in the ASAM Editorial Guide, follow the guidelines in the xref:compendium:writing_guidelines/documentation_processes.adoc#sec-18931c78-0dc9-46a5-9e4d-e00c39c7ce8b[Creating new editorial rules] section to add a missing rule.

== List of editorial rules

This section contains a list of the entire editorial rules.

[format=csv]
|===
include::compendium:example$rules.csv[]
|===

== Headings

This section contains editorial rules on how to create headings.

[#sec-ASM-2]
=== Start headings with a capital letter (ASM-2)

* In headings and captions, only the *first word* begins with an uppercase letter (sentence-style capitalization).
* _Exception_: *Acronyms* and *proper names* are spelled as is.

*Example*

[#tab-07cd91ec-32d0-4890-8276-cbadc0efc6b0]
.Use of uppercase in headings and captions
[%header]
|===
|No                                             |#Yes#
|[.line-through]#Wrong Formatting of a Heading# |Correct formatting of a heading
|[.line-through]#Asam rules to follow#          |ASAM rules to follow
|[.line-through]#Scope of OpenScenario#         |Scope of OpenSCENARIO
|===

*Source*

ASAM Writing Guide: 4.5. Uppercase and lowercase

== Lists

These editorial rules apply to lists:

[#sec-ASM-5]
=== Start each list item in a list with an uppercase letter (ASM-5)

*Example*

```
* This is the first sentence.
* This is the second sentence.
* This is the third sentence.
```

*Exceptions*

If a list item starts with one of the following, do not use an uppercase letter:

* Code elements +
For example: * `<elevation>` elements shall be defined in ascending order according to the s-coordinate.
* Mathematical signs +
For example: * `x` and `y`
* URLs +
For example: * http://www.asam.net

*Source*

ASD-STE100 (2021, issue 8): Rule 4.3 Use a vertical list for complex text, page 1-4-4

[#sec-ASM-6]
=== Put a full stop at the end of a list item if it is a full sentence (ASM-6)

*Example*

[#tab-23063c34-07c7-4ecd-a797-ad8d715df052]
.Use of full stops at the end of a list item
[%header]
|===
|No |#Yes#
|[.line-through]#* This is the first sentence# +
[.line-through]#* This is the second sentence# +
[.line-through]#* This is the third sentence#
|* This is the first sentence. +
* This is the second sentence. +
* This is the third sentence.
|===

*Source*

* ASD-STE100 (2021, issue 8): Rule 4.3 Use a vertical list for complex text, page 1-4-4
* Microsoft Style Guide: https://docs.microsoft.com/en-us/style-guide/scannable-content/lists#punctuation

[#sec-ASM-8]
=== Use lists with similarly structured items for complex text (ASM-8)

Use lists instead of long sentences to present complex text in a way that is easier to read and understand.
The list items shall be a set of similarly structured items.
For example, each item should be a noun or a phrase that starts with a verb.

*Example*

```
The outline of the road marking is described by the attributes @length and @space:

* @length represents the visible part of the line.
* @space describes the non-visible part.
```

*Source*

* ASD-STE100 (2021, issue 8): Rule 4.3 Use a vertical list for complex text, page 1-4-4
* Microsoft Style Guide: https://docs.microsoft.com/en-us/style-guide/scannable-content/lists
* Google Developer Documentation Style Guide: https://developers.google.com/style/lists

[#sec-ASM-9]
=== Just add one sentence per line (ASM-9)

* Insert a line break after each sentence.
* Do not add manual line breaks inside sentences.

*Instruction*

* _"Only hit 'enter' after a period ('.'), but make sure to hit 'enter' after a period."_

*Example*

```
* This is the first sentence.
* This is the second sentence.
* This is the third sentence.
```

*Source*

ASAM Writing Guide: 4.3. One sentence per line

[#sec-ASM-10]
=== Choose a suitable type of list (ASM-10)

==== Use a bulleted list for things that have something in common but don’t need to appear in a particular order.

*Example*

```
The database owner can:

* Create and delete a database.
* Add, delete, or modify a document.
* Add, delete, or modify any information in the database
```

*Source*

Microsoft Style Guide: https://docs.microsoft.com/en-us/style-guide/scannable-content/lists#bulleted-lists

==== Use a numbered list for sequential items (like a procedure) or prioritized items (like a top 10 list).

*Example*

```
To sign on to a database:

1. On the File menu, select Open database.
2. In Username, enter your name.
3. In Password, enter your password, and then select OK.
```

*Source*

Microsoft Style Guide: https://docs.microsoft.com/en-us/style-guide/scannable-content/lists#numbered-lists

[#sec-ASM-11]
=== Do not put punctuation or conjunctions at the end of a list item if it is not a full sentence (ASM-11)

If an item in a list is not a full sentence, then do not put the following punctuation or conjunctions:

* Full stops (periods)
* Semicolons
* Commas
* Conjunctions like and or or

*Example*

[#tab-a099df34-7296-42e1-bd7f-db180f84fe66]
.Use of punctuation and conjunctions at the end of an item
[%header]
|===
|No |#Yes#
|[.line-through]#* Common junctions,# +
[.line-through]#* Direct junctions, and# +
[.line-through]#* Virtual junctions.#
|* Common junctions +
* Direct junctions +
* Virtual junctions
|===

*Source*

* ASD-STE100 (2021, issue 8): Rule 4.3 Use a vertical list for complex text, page 1-4-4
* Microsoft Style Guide: https://docs.microsoft.com/en-us/style-guide/scannable-content/lists#punctuation
* Google Developer Documentation Style Guide: https://developers.google.com/style/lists

== Source code examples

These rules apply to source code examples:

[#sec-ASM-43]
=== Use backticks for inline literals (ASM-43)

* Use pairs of single backticks (` `) for inline literals.
* Do not use pairs of double backticks (\\`` ``).

In AsciiDoc, double backticks are used https://docs.asciidoctor.org/asciidoc/latest/text/monospace/#unconstrained[for text formatting in certain cases].
Unfortunately, this causes poor wording and readability and therefore shall not be used.

*Example*

[#tab-ce27729f-33c4-47b2-a579-e7a1c2434c3a]
.Use backticks for inline literals
[%header]
|===
|No |#Yes#
|[.line-through]#The example below shows the structure of an \\``Act``.#                             |The example below shows the structure of an \`Act`.
|[.line-through]#Movements of vehicles in \\``Act`` are defined in the \``ManeuverGroup``s section.# |Movements of vehicles in \`Act` are defined in the \`ManeuverGroup` section.
|===

*Source*

ASAM Writing Guide: 6.1. Inline literals
