[#top-xil-writing-guide]
//= Writing guide
:numbered:
:toc:


CAUTION: This page is still a DRAFT version (V1.6) and subject to change!


[.lead]
This guide is intended to help you writing content for the ASAM XiL project.
It provides you a set of hints and rules that make it easier to contribute concise and homogeneous content and documents to the project.

== Language

=== Use American English (AE)

* Use "English (US)" (ISO: *en-US*) as a language setting in your text editor.
* Mnemonic: -or, -l, -yze, -er

[#tab-osc2-writing-guide-ae]
.American English
[%header, cols="^10,^10", align="right"]
|===
|No                         |#Yes#
|[.line-through]#colour, behaviour#    |color, behavior
|[.line-through]#labelling# |labeling
|[.line-through]#analyse#   |analyze
|[.line-through]#centre#    |center
|===


=== Verbs with a special meaning (shall, should, may, can)

* Use these modal verbs to express the level of obligation:

[#tab-osc2-writing-guide-modal-verbs]
.Proper modal verbs
[%header, cols="^10,^10,^20", align="right"]
|===
|Level of obligation |Verb to use |Colloquial meaning

|*_Requirement_*
|#*shall, +
shall not*#
|mandatory statement, +
"it must do/have", +
"it is not allowed to do/have"

|*_Recommendation_*
|#*should, +
should not*#
|"it is good/bad practice to do/have"

|*_Permission_*
|#*may*#
//, +
//need not*#
|"it is allowed to do/have and also allowed not to do/have"

|*_Possibility_*
|#*can, +
cannot*#
|"it depends on some circumstances if or if not"

|===

NOTE: The differences between these verbs are subtle and sometimes difficult to grasp.
The table <<tab-osc2-writing-guide-modal-verbs, with modal verbs>> is based on ISO guidelines but currently under discussion.
It is possible that the table will be simplified in the future.



=== Keep it short

* Write short sentences.
* If sentences get too long, consider splitting them up into shorter sentences.
* Keep headings short (only one line).

[#tab-osc2-writing-guide-shortness]
.Shortness is key
[%header, cols="^10,^10", align="right"]
|===
|No                                                                                                                  |#Yes#
|[.line-through]#3.1 Hints on how to maintain the printer#                                                           |3.1 Printer maintenance
|[.line-through]#Due to the fact that they were able to come to an agreement, a name changing of the file took place.# |The file was renamed.
|===

=== Use present tense

* Present tense is easy to understand.
* Present tense is the preferred tense to express technical facts.

[#tab-osc2-writing-guide-tense]
.Present tense
[%header, cols="^10,^10", align="right"]
|===
|No                                                    |#Yes#
|[.line-through]#Chapter X will describe the details.# |Chapter X describes the details.
|===

=== Use active voice

* Active voice is easier to understand than passive voice.

[#tab-osc2-writing-guide-voice]
.Passive voice and active voice
[%header, cols="^10,^10", align="right"]
|===
|No                                                      |#Yes#
|[.line-through]#The variable is set by the user.#       |The user sets the variable.
|[.line-through]#The car is driven to the garage by me.# |I drive the car to the garage.
|===

== Keep it simple

=== Use simple constructs

* Simple constructs require fewer words and are easier to read.

[#tab-osc2-writing-guide-constructs]
.Simple constructs
[%header, cols="^10,^10", align="right"]
|===
|No                                   |#Yes#
|[.line-through]#in order to#         |to
|[.line-through]#has the possibility to# |can
|===

=== Do not use abbreviations

* Some less common abbreviations may confuse the reader.
Avoid them.

[#tab-osc2-writing-guide-abbreviations]
.No abbreviations
[%header, cols="^10,^10", align="right"]
|===
|No                    |#Yes#
|[.line-through]#e.g.# |for example
|[.line-through]#i.e.# |meaning
|===

== Be precise

=== Do not use synonyms

* Stick to the same word for an element or concept.

[#tab-osc2-writing-guide-consistency]
.Use words consistently
[%header, cols="^10,^10", align="right"]
|===
|No |#Yes#
|[.line-through]#Press the _key_. After hitting the _button_ the pop-up appears.# |Press the _key_. After pressing the _key_ a pop-up appears.
|===

=== Avoid words that are not precise

* Do not use words like "[.line-through]#basically#", "[.line-through]#actually#", "[.line-through]#very#", "[.line-through]#practically#", ...

=== Use 'that' and 'which' correctly

* Use *'that'* and *'which'* to express the information level:
** *_'that'_* adds essential information, no commas are used.
** *_'which'_* adds information that can be left out, commas are used.

[#tab-osc2-writing-guide-precision]
.Precision matters
[%header, cols="10,^10,^10", align="right"]
|===
|Information|No                                                             |#Yes#
|Essential: Talking about that specific car they own.|[.line-through]#The car they own is old. +
The car which they own is old.#                             |The car that they own is old.
|Additional: The color of the car is not an essential information.|[.line-through]#The vehicle that is red drives down the road.# |The vehicle, which is red, drives down the road.
|===

=== Use 'since' and 'because' correctly

* Only use _'since'_ to refer to a point in time.

 Errors since startup.

* Always use _'because'_ to express reason.
(_Since_ can lead to ambiguity if used to express reason, see example.)

[#tab-osc2-writing-guide-precision2]
.Since and because
[%header, cols="^10,^10", align="right"]
|===
|No |#Yes#
|[.line-through]#The system cannot calculate a result, *_since_* the data is missing.# +
(time duration or cause?)| The system cannot calculate a result, because the data is missing.
|===


== Formatting

=== Consistent formatting

* Stick to _one spelling_ for a word that allows several spellings. +
(For example, _e-mail_, _email_, or _E-mail_.)
* Stick to _one style_ to present information. +
(For example, steps are always presented as a numbered list.)
* Stick to _one formatting_ for a special purpose. +
(See <<Typographic conventions for XiL>> for more details.)


=== Typographic conventions for XiL

AsciiDoc offers markup characters for words and terms.
Here is how to use them correctly _in the floating text_ for XiL:

* _Italic_
** Markup character: Underscore (_)
*** Example: `+++_term_+++`
** Use italic in the following cases:
*** For glossary terms
*** For new terms
*** To emphasize terms
* _Code elements_
** Markup character: Backtick (\`)
*** Example: `+++`term`+++` +
** Use code elements for:
*** Names of classes
*** Names of attributes
*** Names of parameters
*** One-line code examples
*** File names
** For plural forms: Never add a plural _'-s'_ to code element names. Use _"instances/elements/objects/types of <name>"_ instead.
+
[#tab-xil-writing-guide-code-elements]
.Code elements plural forms
[%header, cols="^10,^10", align="right"]
|===
|No                                                                           |#Yes#
|[.line-through]#Create six `MyVector`**s**.# |Create six instances of `MyVector`.
|===

** See <<Source code>> for more details on source code.
* _Bold_
** Markup character: Asterisk (*)
*** Example: `+++*term*+++`
** Do not use bold for terms in floating text.
** This markup is reserved for
*** Structuring elements, like sub-headings that should not appear in the table of contents.
*** Emphasis, for example single characters in formulae or tables.

=== Punctuation marks

Asciidoc renderers take care of a typographically correct output.
Therefore it is sufficient to use the following characters for punctuation marks:

* Quotation marks
** Use normal double quotation marks `+++"+++` (ASCII #34, Unicode U+0022). +
The character can be found on the keyboard (Shift-2).
** Never use single quotation marks.

* Apostrophes
** Use normal apostrophes `+++'+++` (ASCII #39, Unicode U+0027). +
The character can be found on the keyboard (Shift-&#35;).

* Hyphen
** Use the minus sign `-` (ASCII #45, Unicode U+002D) for hyphen. +
The character can be found on the keyboard (-).

* Dashes
** Use the minus sign `-` (ASCII #45, Unicode U+002D) for dashes. +
The character can be found on the keyboard (-).

Do _not_ use other typographic characters like rounded quotation marks, en-dashes and so on.

////

=== Use templates

* Adoc-templates are available for common types of topics.
Use them to create consistent content.
* Each template contains instructions on how to use the template and sample text that has to be replaced.
* Currently available templates:
** <<../template/generic_template.adoc, Generic>>
** <<../template/task_template.adoc, Task>>
** <<../template/uml_element_template.adoc, UML element>>
** <<../template/use_case_template.adoc, Use case>>

////

=== One sentence per line

* Insert a line break after each sentence.
* No manual line breaks inside sentences.

=> _"Only hit 'enter' after a period ('.'), but make sure to hit 'enter' after a period."_

```
1 This is the first sentence.
2 This is the second sentence.
3 This is the third sentence.
```

=== Use paragraphs

* Use paragraphs to structure your text.
* A new thought or statement requires a new paragraph.
* An empty line creates a new paragraph.

```
1 This is the first sentence of the first paragraph.
2 This is the second sentence of the first paragraph.
3
4 This is the first sentence of the second paragraph.
```

=== Manual line breaks

* Use manual line breaks sparingly.
* To force adoc to make a line break within a paragraph, end the line before the break with a space followed by a plus sign (` +`).

```
After this sentence a line break is needed. +
This sentence appears on a new line.

* Useful for lists +
Detailed explanations begin in a new line after the main list element.
```
====
After this sentence a line break is needed. +
This sentence appears on a new line.

* Useful for lists +
Detailed explanations begin in a new line after the main list element.
====


=== Uppercase and lowercase

* In headings and captions only the *first word* begins with an uppercase letter (sentence-style capitalization).
* _Exception_: *Acronyms* and *proper names* are spelled as is.

[#tab-osc2-writing-guide-headings]
.Use of uppercase in headings and captions
[%header, cols="^10,^10", align="right"]
|===
|No                                             |#Yes#
|[.line-through]#Wrong Formatting of a Heading# |Correct formatting of a heading
|[.line-through]#ASAM rules to follow#          |ASAM rules to follow
|[.line-through]#Scope of OpenScenario#         |Scope of OpenSCENARIO
|===

=== Tags (aka anchors)

* All topics, figures, tables and code examples shall have a unique tag:
** `[#top-<uid>]` for topics
** `[#fig-<uid>]` for figures (images, diagrams, and so on)
** `[#tab-<uid>]` for tables
** `[#code-<uid>]` for source code blocks
* Sections may also have a tag `[#sec-<uid>]` if a link to the section is needed.
* Use a semantically fitting string as `<uid>`.
** For the uid-string use a combination of:
*** lowercase letters `a`-`z`
*** numbers `0`-`9`
*** `###todo` as separators
* Some hints to create a unique id:
** Add an abbreviation that corresponds to the name of the main document as part of the id.
For example, add 'pg' for all anchors used in the _P_rogrammers _G_uide.
** For anchors for figures (`#fig-`) it is recommended to use a unique id that has a _relation to the figure name_ (see also <<File names for figures>>).

```
Examples:
[#top-pg-ees-port-introduction]
[#fig-pg-overview22-diagram5]
[#tab-pg-important-elements-of-can]
[#code-pg-protocol-syntax-example1]
[#sec-pg-important-section-to-be-linked-to]
```

=== Indentation
* Use four space characters per indentation level.
* Do not use tab characters.
* Use the following text editor settings:
** *Tab size: 4*
** *Insert spaces*

[#tab-osc2-writing-guide-indentation]
.Four spaces indentation (spaces marked as '.')
[%header, cols="10,10", align="right"]
|===
^|No ^|#Yes#
|Normal text +
[.line-through]#->Level 1 indented text +
->->Level 2 indented text#
|Normal text +
....Level 1 indented text +
........Level 2 indented text
|===

////

=== Non-normative sections

Text sections (paragraphs or blocks of text) in the documentation of a standard are considered **normative**.

If some text sections should be considered as **non-normative** and only descriptive (for example, background information or examples), mark this sections deliberately as non-normative.

* Non-normative sections shall be marked with the user-defined asciidoc role _non-normative_.

** Put the role attribute `+[.non-normative]+` in front of single paragraphs or blocks to mark them as non-normative.

** Inside a normative section use `+[.non-normative]#<text>#+` to mark single text passages `+<text>+` as non-normative.

[#cod-osc2-writing-guide-normative]
.Example for normative and non-normative sections
[source, adoc]
----
This is a normative paragraph.

[.non-normative]
This is a descriptive, non-normative paragraph.

====
This is a normative block.
====

[.non-normative]
====
This is a descriptive block.
====

This is another normative paragraph.
This sentence is normative.
[.non-normative]#This sentence is non-normative.#
This sentence is normative again.
----

* Roles can be combined using the following syntax: `+[.<first_role>.<second_role>]+`.

[#cod-osc2-writing-guide-normative2]
.Example with multiple roles
[source, adoc]
----
[.important.non-normative]
This is a descriptive, non-normative paragraph that is also marked with the important-role.
----

* Id and role attributes can be combined. +
Use the long notation for easier reading: `+[id=<document_id>, role=<document_role>]+`.

[#cod-osc2-writing-guide-normative3]
.Example with role and id combined
[source, adoc]
----
[id=top-doc-unique-id, role=non-normative]
= Document title

This is a descriptive, non-normative document.
----

* The actual format and style of non-normative sections depends on the entry in the CSS style sheet file that is used for rendering the text and is not coded in the adoc-file itself.

[#cod-osc2-writing-guide-css-example]
.Example of a CSS entry for non-normative text
[source, css]
----
.non-normative { font-style: italic; color: darkgreen; background: gold }
----

////


== File handling

=== File names

* Use only *lowercase* for file and folder names.
* Use the underscore '###todo' instead of 'space' in file and folder names.
* Use `.adoc` as file ending for documents.

[#tab-osc2-writing-guide-file-names]
.Use of uppercase and underscores in file and folder names
[%header, cols="^10,^10", align="right"]
|===
|No                                      |#Yes#
|[.line-through]#ExampleFileName.adoc#   |example_file_name.adoc
|[.line-through]#Another file name.adoc# |another_file_name.adoc
|[.line-through]#Writing_guide.adoc#     |writing_guide.adoc
|===

=== File names for figures

* The _file name_ of a figure shall be the same as the _caption_ of this figure, with the following adaptions:
** Use only _lowercase_ letters for the file name.
** Use `###todo` as separators.

*Example:*
====
*Figure headline:* +
"Port definition interfaces of the XYZ framework configuration object model"

*File name:* +
###todo

//port-definition-interfaces-of-the-xyz-framework-configuration-object-model.svg

//port_definition_interfaces_of_the_xyz_framework_configuration_object_model.svg

====


=== File formats

* _UML diagrams_ must be provided as _PlantUML files_ (`+*.puml+`).

* Charts and other diagrams shall preferably be provided as _scalable vector graphics_ (`+*.svg+`).
Alternatively, _portable network graphics_ (`+*.png+`) may also be used.

* Do not use figure file formats other than PlantUML, SVG or PNG.

=== Directory structure

* Each adoc-file is placed in a separate folder that is named after the contained adoc-file.

* Use one file per topic for larger chapters.

* Image files are kept per adoc-file.
They are stored in a sub-folder called "images" next to the adoc-file.

.Example directory structure
----
├───food
│   ├───fruit
│   │   ├───apples
│   │   │   ├───images
│   │   │   │   ├───wellant.svg
│   │   │   │   ├───golden_delicious.svg
│   │   │   │   ├───gala.png
│   │   │   └───apples.adoc
│   │   │
│   │   ├───berries
│   │       ├───images
│   │       │   ├───blueberries.png
│   │       │   ├───gooseberries.svg
│   │       │   ├───goji.svg
│   │       ├───berries_introduction.adoc
│   │       ├───berries_definitions.adoc
│   │       └───berries_examples.adoc
│   │
│   └───vegetables
│   │   ├───potatoes
│   │   │   └───images
│   │   │   │   └───...
│   │   │   └───potatoes.adoc
...
----

== Additional elements

=== Lists

* Lists are a great way to present lots of similar information in a compact form.

==== Numbered lists
* Use *numbered lists* (AsciiDoc `*.*`) for steps that require a specific order.

.A numbered list example
```
. First step
. Second step
. Third step
```

====
. First step
. Second step
. Third step
====

==== Bullet point lists
* Use *bullet points* (AsciiDoc `***`) for enumerations and elements that do not require a specific order.

.A bullet point list example
```
* Two apples
* One banana
* One orange
```
====
* Two apples
* One banana
* One orange
====

==== Lists inside lists

* You can use lists inside lists and define several levels of sub-lists.

.A complex numbered list example
```
. First step
.. First sub-step
.. Second sub-step
... First step inside second sub-step
... Second step inside second sub-step
.. Third sub-step
. Second step
. Third step
```

====
. First step
.. First sub-step
.. Second sub-step
... First step inside second sub-step
... Second step inside second sub-step
.. Third sub-step
. Second step
. Third step
====

.A complex bullet list example
```
* Bullet one
* Bullet two
** Sub-bullet one
** Sub-bullet two
*** Sub-sub-bullet one
** Sub-bullet three
* Bullet three
```

====
* Bullet one
* Bullet two
** Sub-bullet one
** Sub-bullet two
*** Sub-sub-bullet one
** Sub-bullet three
* Bullet three
====

==== List formatting conventions

* Introduce lists with complete sentences, ending with a colon.
* Start all list items with an uppercase letter.
* Ensure similar structure for all list items, for example, whole sentences vs. nouns.
* End sentences with a period.

* Do not use closing punctuation for single words, noun phrases, verbs, adjectives, etc.

* Do not write lists as a continuous sentence.
* In bulleted and numbered lists, end each list item with a period if the following applies:
** Any item forms a complete sentence when combined with the list introduction that precedes the colon.
** Exception: Do not use periods if all items have three or fewer words or if the items are UI labels, headings,
subheadings, or strings.
** Any item by itself is a complete sentence.
* Do not use semicolons, commas, or conjunctions (like _'and'_ or _'or'_) at the end of list items.

Examples of correctly formatted lists:
====
My pets like the following:

* My cat likes to hunt in the fields.
* My dog is happy when we go out for a walk.
* My guinea pig wants to sleep all day.
====

====
I like the following types of fruit:

* Apples
* Bananas
* Cherries
====

=== Figures

Figures - like images, pictures or drawings - may be used to illustrate complex facts.

* Preferred format: `.svg`
* Alternative format: `.png`
* Figures are stored in a sub-folder named `images` located inside the chapter folder.
See also <<Directory structure>>.
* The name of the image file shall match the anchor name (excluding the `fig-` prefix)
* The exact adherence to this syntax is absolutely necessary for the automatic generation of the list of figures at the end of the document.


==== Images

* Each image shall have:
** A tag starting with `#fig-`
** A caption
** The `image::`-link to the picture
** An alternative text

```
[#fig-<id>]
.<caption>
image::<filename>[<alternative text>]
```
Example:
```
[#fig-project-structure]
.Overview of the project structure
image::project-structure.svg[]
```

==== Attribute 'imagesdir'

* Set the `:imagesdir:` only in the root adoc-file that compiles all the adoc-files into a single document (the so-called _mapping-file_ `main.adoc`).
* With each include in the root document, the imagesdir must be set to the parent-folder of the images-folder of the included adoc-file.

[IMPORTANT]
====
Despite its name, the attribute *:imagesdir:* shall _not_ contain the name of the images-folder itself, but the *name of the parent-folder of the images-folder*.

This way, the images are displayed in an adoc-preview, even if only the sub-topic is opened. No need to open the main.doc all the time for image previews.
====

Example for main.adoc:
```
 :imagesdir: apples
 include::apples/apples.adoc[leveloffset=+1]

 :imagesdir: berries
 include::berries/berries_introduction.adoc[leveloffset=+1]
 include::berries/berries_definitions.adoc[leveloffset=+1]
 include::berries/berries_examples.adoc[leveloffset=+1]

or:

 :workdir: apples
 :imagesdir: {workdir}
 include::{workdir}/apples.adoc[leveloffset=+1]
 ...
```

* Do _not_ set the attribute imagesdir in subordinated adoc-files.
Paths in the image-macros are relative to the adoc file.
The image-macros also work when previewing only a single subordinated adoc file.


==== PlantUML diagrams
* PlantUML diagrams are included as a file.
* Each diagram shall have:
** A tag starting with `#fig-`
** A caption
** The block format identifier `[plantuml]`
** The `include::`-link, surrounded by block markers `----`
** An alternative text

....
 [#fig-<id>]
 .<caption>
 [plantuml]
 ----
 include::<filename.puml>[]
 ----
....

Example:
....
 [#fig-root-package-class-diag]
 .Class diagram for the root package
 [plantuml]
 ----
 include::my-class-diagram.puml[class diagram for root package]
 ----
....

==== Attribute 'plantuml-format'

* The images generated from the PlantUML diagrams during the creation of the output document shall have SVG format.
This is globally configured with the document attribute `:plantuml-format:` in the document header.
+
Example:
```
[#top-my-document]
= My document
:description: A generic document
:revdate: 2020-03-13
...
:plantuml-format: svg
```

=== Tables

* Use tables if you have to present a huge amount of similar data in a compressed form.
* A table shall have:
** A tag
** A caption

```
[#tab-uid]
.This is the caption of the table
|===
|cell 1_1 | cell 1_2 | cell 1_3
|cell 2_1 | cell 2_2 | cell 2_3
|cell 3_1 | cell 3_2 | cell 3_3
|===
```

====
[#tab-uid]
.This is the caption of the table
|===
|cell 1_1 | cell 1_2 | cell 1_3
|cell 2_1 | cell 2_2 | cell 2_3
|cell 3_1 | cell 3_2 | cell 3_3
|===

====

* Nested tables are also possible.

```
[cols="2,2a"]
|===
| col 1 | col 2
| cell 1.1 | cell 1.2
| cell 2.1 | cell 2.2
[cols="1,1"]
!===
! n_col 1 ! n_col 2 ! n_c 11 ! n_c 12
!===
|===
```

====
[cols="2,2a"]
|===
| col 1 | col 2
| cell 1.1 | cell 1.2 | cell 2.1 | cell 2.2
[cols="1,1"]
!===
! n_c 1.1 ! n_c 1.2 ! n_c 2.1 ! n_c 2.2
!===
|===
====

* AsciiDoc offers a huge amount of attributes to build more complicated tables and to affect the style of tables.
See https://docs.asciidoctor.org/asciidoc/latest/tables/table-ref/ for details.
* Some useful examples for table formatting:
** Span cells by using the _span factor_ and _span operator_ of the cell specifier. +
(Examples: `3+|`: Cell spans three columns, `.2+|`: Cell spans two rows.)

NOTE: Using cell spans may cause border frame displaying issues. Use sparingly.

** Adjust the column width with the column attribute `[cols="<n>,<m>"]`, using the numbers n and m to define the relative width between the columns. +
(Example: `cols="2,4"`: Second column is twice as wide as the first one.)

=== References

* The format of references in the text is fixed and depends on the type of element the reference points to:
+
[#tab-osc2-writing-guide-types-of-references]
.Types of references and their format
[%header, cols="5,10,10", align="right"]
|===
^|Type
^|No
^|#Yes#
|Table
|[.line-through]#See *Table-Name* +
See following table#
|See *Table x*
|Figure
|[.line-through]#See *Figure-Name* +
See follwing figure#
|See *Figure x*
|Chapter
|[.line-through]#See Chapter *x.y* +
See Chapter *Chapter-Name* +
See Section *x.y* +
See Section *Chapter-Name* +
See *x.y Chapter-Name* +
See *x.y*#
|See *Chapter-Name*
|Appendix
|
|See *Appendix-Name*
|Bibliography
|
|See *[x]*
|===


* Use `xref:<tag>[{<style>}]` for references.
** `<tag>` The destination tag.
** `<style>` Type-specific style for the reference:
*** `fig-style` Reference to figure
*** `tab-style` Reference to table
*** `top-style` Reference to chapter
*** `sec-style` Reference to other destinations
* Examples
** `+++See xref:top-an-important-chapter[{top-style}] for details.+++`
** `+++See xref:fig-a-nice-figure[{fig-style}] for details.+++`


=== Special characters

Sometimes you may need to display a character that is reserved for adoc-formatting.
Here is how to do it.

* *Underscore (&lowbar;)* +
Use `+&lowbar;+` to display an underscore.
* *Pound sign (&#35;)* +
Use `+&#35;+` to display a pound sign.
* *Check mark (&#10004;)* +
Use `+&#10004;+` to display a check mark.
* *Protected space ({nbsp})* +
Use `+{nbsp}+` to define a space character is not used for automatic line breaks. +
This is especially useful for value-unit-pairs like `+5{nbsp}m/s+` (5{nbsp}m/s) to ensure that value and unit are always in the same line of text.
* *Word joiner ({wj})* +
Use `+{wj}+` to glue two words together.
This is useful to enhance readability, for example when adding footnotes (`+term{wj}footnote:[text]+`).

=== Control elements for PDF-renderer

* A *page break* can be forced using `<<<`.
Use sparingly.
* The *page orientation* can be specified by using the roles `[.portrait]` and `[.landscape]`.

== Source code

Consider one of the following possibilities if you want to add source code examples to an adoc topic.

. You may use small bits of code as an <<Inline literals, *inline literal*>> directly inside your text.
. You may add source code as a <<Source code fragments, *fragment*>> from a source code file by reference.
. You may copy and paste source code directly as a <<Source code snippets, *snippet*>> into the adoc topic.

=== Inline literals

For very small bits of code using *inline literals* is the most convenient way to add source code examples.
This type of including source code is especially useful if you want to highlight single code elements like methods or class names.

==== Changes in the adoc file

Enclose the source code in a *pair of pluses surrounded by a pair of backticks*, like this:

 Call the `+source_example_func()+` for the result.

==== Result
The previous line looks like this as adoc output:

====
Call the `+source_example_func()+` for the result.
====

=== Source code fragments

You can add source code as a *fragment* from a source code file if you would like to reference to the source code within the source code file.

There are several advantages of using fragments:

* You do not need to copy the source code into the documentation.
* You are referencing to the single point of truth, which is the source code file.
* If you apply changes to the source code file, these changes are automatically applied to your documentation.

Follow these steps to add source code fragments to your documentation:

. Add source comment tags at the beginning and the end of the part of code you want to use in your code block.
. Use this tag to include the fragment into the adoc documentation.

The example in the following subchapters uses the tag `exampleInclude` to add a code fragment.

==== Changes in the source code file

[#code-tags-in-source-file]
.Tags for the inclusion of source code from a source code file
[source, osc2]
----
[...]
// tag::exampleInclude[]    <1> <2>
function lorem(ipsum, dolor = 1) {
    const sit = ipsum == null ? 0 : ipsum.sit;
    dolor = sit - amet(dolor);
    return sit ? consectetur(ipsum, 0, dolor < 0 ? 0 : dolor) : [];
}
// end::exampleInclude[]    <3>
[...]
----

<1> To indicate the start of a tagged region in the source code file, insert a comment line in the source code.
<2> Assign a name to the tag directive.
In this example, the tag is named `exampleInclude`.
<3> Insert another comment line where you want the tagged region to end.

==== Changes in the adoc file

....
[#code-example-code-block-tag]    <1>
.ASAM example code block included by tags    <2>
[source, osc2]    <3>
----    <4>
include::resources/examplecode.js[tags=exampleInclude]    <5>
----    <6>
....

<1> Insert an anchor for the code block
You can reference this anchor using \<<code-example-code-block-tag>>
<2> Insert a caption for the code block.
<3> Define the source code language for code highlighting.
For example, `osc2`, `xml`, or `java`.
<4> Insert a code block delimiter.
<5> Directly include the source code within the source code file with a tag marking fragment.
<6> Insert a code block delimiter.

NOTE: For more information see the https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/[Asciidoctor reference].

==== Result

This is how the reference looks like inside the adoc file:

====
[#code-example-code-block-tag]
.ASAM example code block included by tags
[source, osc2]
----
include::resources/examplecode.js[tags=exampleInclude]
----
====

=== Source code snippets

You can add source code as a *snippet* into your adoc documentation if you cannot or if you do not want to reference to the source code file.
Be aware that you have to maintain two places (your original code and the snippet in the adoc) in case of future changes.

Follow these steps to use source code as a snippet:

. Copy the part of source code you want to use as a snippet.
. Paste the snippet into your adoc file.
. Insert an anchor, a caption, the highlighting info and delimiters as shown in the following subchapter.

==== Changes in the adoc file
....
[#code-example-code-block]    <1>
.ASAM example code block included in an asciidoc file    <2>
[source, osc2]    <3>
----    <4>
<ParameterDeclarations>    <5>
  <ParameterDeclaration name="$HostVehicle" parameterType="string" value="car_white"/>
  <ParameterDeclaration name="$TargetVehicle" parameterType="string" value="car_red"/>
  <ParameterDeclaration name="$EgoStartS" parameterType="double" value="50"/>
  <ParameterDeclaration name="$HeadwayTime_LaneChange" parameterType="double" value="0.4"/>
  <ParameterDeclaration name="$HeadwayTime_Brake" parameterType="double" value="1.0"/>
</ParameterDeclarations>
----    <6>
....
<1> Insert an anchor for the code block.
Reference this anchor using \<<code-example-code-block>>
<2> Insert a caption for the code block.
<3> Define the source code language for code highlighting.
For example, `osc2`, `xml`, or `java`.
<4> Insert a code block delimiter.
<5> Insert the code block.
<6> Insert a code block delimiter.

==== Result

This is how the correctly configured snippet looks like in the adoc file:

====
[#code-example-code-block]
.ASAM example code block included in an asciidoc file
[source, osc2]
----
<ParameterDeclarations>
  <ParameterDeclaration name="$HostVehicle" parameterType="string" value="car_white"/>
  <ParameterDeclaration name="$TargetVehicle" parameterType="string" value="car_red"/>
  <ParameterDeclaration name="$EgoStartS" parameterType="double" value="50"/>
  <ParameterDeclaration name="$HeadwayTime_LaneChange" parameterType="double" value="0.4"/>
  <ParameterDeclaration name="$HeadwayTime_Brake" parameterType="double" value="1.0"/>
</ParameterDeclarations>
----

====

=== Line numbers and references

You can refer to lines of code in two ways:

* Use callouts to refer to single lines.
* Use automatic line numbering.


==== References to single lines

Use _Asciidoc callouts_ to refer to lines of source code, for example to add a detailed explanation after the code block.

. Add a comment with a _reference number in angle brackets_ at the end of the line in the source block: +
 `# <x>` +
(x = 1, 2, ...) +
Marking the reference number as a comment allows users to copy-and-paste the code as working code.
. _After_ the source block repeat the number in angle brackets, followed by the explanation text.

*Example:*
[source, asciidoc, subs=-callouts]
....
[source, osc2, linenums]
----
A normal line
A line with a callout # <1>
Another normal line
Another line with a callout # <2>
----
<1> The explanation for the first callout.
<2> The explanation for the second callout.
....

*Result:*

====
[source, osc2, linenums]
----
A normal line
A line with a callout # <1>
Another normal line
Another line with a callout # <2>
----
<1> The explanation for the first callout.
<2> The explanation for the second callout.
====

==== Automatic line numbering

An automatic line numbering mechanism is also available, for example to refer to the code later in the text.

. Use `[source, osc2, linenums]` as a source block identifier to enable line numbering.

. Later in the text use the anchor of the code example together with the line number to refer to the line: +
`+In <<code-uuid, name of the example>>, line x, ...+`


=== Pipeline artifacts as reference
Please note that any preview of a tool is just for your convenience. +
*The only reliable documents for reviews are the pdf-artifacts generated by the CI-pipeline!* +
These artifacts are linked at the main Gitlab-page of the project.
You can also download the artifacts directly from the pipeline result page.

== Related topics

* For a short introduction to AsciiDoc, see the https://code.asam.net/simulation/resources/-/blob/master/asciidoc_tutorial/asciidoc_tutorial.adoc[AsciiDoc Guide].
