= Roles At ASAM - Overview
:description: Links to the current contact page for ASAM Office members.
:keywords: roles, asam new-here-content

Every ASAM Project has mandatory and optional roles, the optional roles depend on the size and the structure of the project.

ASAM projects have a couple of standard roles:

ASAM Global Technology Manager (GTM):: A GTM is an ASAM employee focussed on coordinating project processes and the background work behind a project.
ASAM Standard User:: An ASAM Standard User is someone that is part of the ASAM community but not involved in the project development at hand.
Workgroup (WG) Member:: An ASAM User that is involved directly in the development of an ASAM standard. They are a participant in a workgroup (WG) of a standard, a subdivision of the overall project.
Workgroup (WG) Leader:: The WG member that leads the respective workgroup.
Project Lead:: The person responsible for leading and coordinating all project activities. Normally, this position is filled by one of the leading project members in the project.
Technical Steering Committee (TSC) Member:: A member of committee responsible for approving or rejecting projects and proposals.
Reviewer:: An ASAM Standard User or WG Member that reviews a draft or release candidate for a new or updated standard.
Technical Writer:: Formats and writes the document(s) of the standard based on the provided input from the WG members in a formalized and standard-conform way.
Service Provider:: Provides additional services necessary for the standard development.

.Roles within ASAM Projects
|===
|Role               |required       | comment
|GTM                |mandatory      | every project needs one responsible GTM within ASAM
|Project Member     |mandatory      | every project needs project members from at least three different companies
|Project Lead       |mandatory      | without an elected project lead the project may not start. The project lead is a project member elected by the project members to become the project lead.
|Workgroup Member   |optional       | if the project is split up into smaller working groups, a project member can join a workgroup to become a workgroup member
|Workgroup Lead     |optional       | if the project is split up into smaller working groups, a project member can be elected to be the workgroup lead and will support the project lead.
|Service Provider   |optional       | if the project needs additional resources a service provider can be hired, this requires approved budget by the TSC
| Technical Writer  |optional       | if the project requires a technical writer either the ASAM technical writer will fill this role or a service provider can be hired to fill that role.
|===

.Roles around ASAM Projects
|===
|Role               | comment
|TSC                | The TSC is responsible to approve budget, and project as well as releases of project results, such as standards or concept papers
|Standard User      | Someone who is using the ASAM standard
|Reviewer          | A Standard user that want to provide feedback either in a review phase or afterwards
|===
