@startuml
package compendium #ff5050 {
rectangle "nav.adoc" as f0_1
rectangle "antora.adoc" as f0_2
rectangle "antora/build-antora-locally.adoc" as f0_4
rectangle "docker/run-docker.adoc" as f0_6
rectangle "docker/standard-docker-config.adoc" as f0_7
rectangle "docker/wsl.adoc" as f0_8
rectangle "git/cloning-repo-tutorial.adoc" as f0_9
rectangle "git/commit-guidelines.adoc" as f0_10
rectangle "git/git-actions.adoc" as f0_11
rectangle "git/git-terminology.adoc" as f0_12
rectangle "git/maintain-a-repo.adoc" as f0_13
rectangle "git/merge-conflicts.adoc" as f0_14
rectangle "git/merge-requests.adoc" as f0_15
rectangle "git/merge.adoc" as f0_16
rectangle "git/review-code.adoc" as f0_17
rectangle "git/submodules.adoc" as f0_18
rectangle "git/transitioning-to-a-new-workflow.adoc" as f0_19
rectangle "git/working-with-git.adoc" as f0_20
rectangle "git/write-a-feature.adoc" as f0_21
rectangle "git/submodules/submodule-pull.adoc" as f0_22
rectangle "git/submodules/submodules-add.adoc" as f0_23
rectangle "git/submodules/submodules-changing-remote.adoc" as f0_24
rectangle "git/submodules/submodules-switch-version.adoc" as f0_25
rectangle "gitlab/ASAM-Issue-and-MR-Labels.adoc" as f0_26
rectangle "gitlab/Branch-Naming-Conventions.adoc" as f0_27
rectangle "gitlab/Branching.adoc" as f0_28
rectangle "gitlab/cloning-a-repository.adoc" as f0_29
rectangle "gitlab/commit-guidelines.adoc" as f0_30
rectangle "gitlab/Forking.adoc" as f0_31
rectangle "gitlab/gitlab-ide-guide.adoc" as f0_32
rectangle "gitlab/gitlab-terminology.adoc" as f0_33
rectangle "guides/Accessing_Compiled_Artifacts.adoc" as f0_34
rectangle "guides/Meeting-Guidelines.adoc" as f0_35
rectangle "guides/Platforms.adoc" as f0_36
rectangle "guides/ProjectGuidelines.adoc" as f0_37
rectangle "guides/WhatIsYaml.adoc" as f0_38
rectangle "guides/Workflow.adoc" as f0_39
rectangle "guides/WritingGuidelines.adoc" as f0_40
rectangle "implementers-forum/Feedback-Guide.adoc" as f0_41
rectangle "implementers-forum/Scenario-Writers-Guide.adoc" as f0_42
rectangle "open-source/ASAM-DCO.adoc" as f0_43
rectangle "powershell/cloning-a-repository.adoc" as f0_44
rectangle "powershell/powershell-basics.adoc" as f0_45
rectangle "powershell/run-docker.adoc" as f0_46
rectangle "sharepoint/links.adoc" as f0_47
rectangle "sharepoint/synchronizing-sharepoint-with-onedrive.adoc" as f0_48
rectangle "teams/email-notifications.adoc" as f0_49
rectangle "teams/meetings-in-teams.adoc" as f0_50
rectangle "teams/obtain-channel-email.adoc" as f0_51
rectangle "teams/polls-and-surveys.adoc" as f0_52
rectangle "teams/receive-notifications.adoc" as f0_53
rectangle "teams/teams-channel-file-structure.adoc" as f0_54
rectangle "vscode/Adding-Diagrams-To-VSCode.adoc" as f0_55
rectangle "vscode/cloning-a-repository.adoc" as f0_56
rectangle "vscode/recommended-vscode-extensions.adoc" as f0_57
rectangle "vscode/recommended-vscode-settings.adoc" as f0_58
rectangle "vscode/run-docker.adoc" as f0_59
rectangle "vscode/vscode-activity-bar.adoc" as f0_60
rectangle "vscode/vscode-command-palette.adoc" as f0_61
rectangle "vscode/VSCode-Git-Interaction.adoc" as f0_62
rectangle "vscode/vscode-install-extension.adoc" as f0_63
rectangle "vscode/vscode-interface.adoc" as f0_64
rectangle "writing_guidelines/AsciiDoc-Guide.adoc" as f0_65
rectangle "writing_guidelines/coding_style_guide.adoc" as f0_66
rectangle "writing_guidelines/plantuml_documentation_guide.adoc" as f0_67
rectangle "writing_guidelines/writing_guide.adoc" as f0_68
}
package getting-involved #5050ff {
rectangle "nav.adoc" as f1_1
}
package getting-started #50ff50 {
rectangle "about_guide/intentions-and-content.adoc" as f2_6
rectangle "about_guide/using-this-guide.adoc" as f2_7
rectangle "about_guide/working-on-the-guide.adoc" as f2_8
rectangle "new_here/asam-contacts.adoc" as f2_9
rectangle "new_here/current-projects.adoc" as f2_10
rectangle "new_here/how-asam-works.adoc" as f2_11
rectangle "new_here/processes-and-workflows-overview.adoc" as f2_12
rectangle "new_here/roles-overview.adoc" as f2_13
rectangle "new_here/tools-overview.adoc" as f2_14
rectangle "quick_setup/docker-standard.adoc" as f2_15
rectangle "quick_setup/git-standard.adoc" as f2_16
rectangle "quick_setup/microsoft-teams-standard.adoc" as f2_17
rectangle "quick_setup/sharepoint-standard.adoc" as f2_18
rectangle "quick_setup/vscode-standard.adoc" as f2_19
}
package project-guide #ffff50 {
rectangle "macros/macro-pages.adoc" as f3_14
rectangle "macros/macro-reference.adoc" as f3_15
rectangle "macros/macro-related.adoc" as f3_16
}
package role-specific #ff50ff {
rectangle "nav.adoc" as f4_1
rectangle "gtm.adoc" as f4_3
rectangle "project-lead.adoc" as f4_5
rectangle "reviewer.adoc" as f4_6
rectangle "service-provider.adoc" as f4_7
rectangle "standard-user.adoc" as f4_8
rectangle "wg-member.adoc" as f4_10
}
package ROOT #5050d0 {
rectangle "1nav.adoc" as f5_1
rectangle "nav.adoc" as f5_2
rectangle "linking-test.adoc" as f5_4
}
package tooling #d0d050 {
rectangle "calendar/calendar-best-practices.adoc" as f7_11
rectangle "calendar/calendar-setup.adoc" as f7_12
rectangle "docker/docker-best-practices.adoc" as f7_13
rectangle "docker/docker-guides.adoc" as f7_14
rectangle "docker/docker-setup.adoc" as f7_15
rectangle "git/git-best-practices.adoc" as f7_17
rectangle "git/git-guides.adoc" as f7_18
rectangle "gitlab/gitlab-guides.adoc" as f7_20
rectangle "gitlab/gitlab-setup.adoc" as f7_21
rectangle "teams_and_sharepoint/teams-and-sharepoint-best-practices.adoc" as f7_22
rectangle "teams_and_sharepoint/teams-and-sharepoint-guides.adoc" as f7_23
rectangle "teams_and_sharepoint/teams-and-sharepoint-setup.adoc" as f7_24
rectangle "vscode/vscode-guides.adoc" as f7_25
rectangle "vscode/vscode-setup.adoc" as f7_26
}


@enduml