= Join a webinar
:description: Describes how to join an ASAM webinar.
:keywords: webinar, REVIEWED_OK

include::partial$_attributes.adoc[]
include::{abb}[]

{role-standard-user}

TIP: Current webinars are listed on the https://www.asam.net/conferences-events/upcoming-events/[ASAM website^].

== Context
You are interested in a particular standard or project at ASAM but not directly involved in it? +
A webinar is a great opportunity to get insight into the project or standard and give feedback or get some tips for its application.

== Result
You have successfully signed up for the webinar.

== Prerequisites
None

== How
. Go to the https://www.asam.net/conferences-events/upcoming-events/[ASAM website^] and find the webinar you are interested in.
. Access the "Registration" tab, fill out the form and send it to register.
+
You will receive a confirmation email if your registration was successful.


== Troubleshooting / Known Issues
=== I cannot find the event online, but I know it exists
If you want to join a webinar but cannot find the event on the website, you can also contact mailto:info@asam.net[ASAM office] directly.
Please consider this as a last resort to fall back to only in case you cannot find the information.


related::webinar[]