= Adding A New Module
:description: Describes how to add a new module to the ASAM Project Guide so that it contains all importantn infos and structures by default for Antora to build correctly.
:keywords: antora,guide,module,new-content-guide

include::partial$_attributes.adoc[]
include::{abb}[]

== Add mandatory folders and files
To add a new module to the Project Guide, follow these instructions:

. Copy the folder "reference-module-folder" located in the "examples" folder of the "project-guide" module with all its files and subfolders into the "modules" folder

. Rename the folder to be the name of the new module
+
TIP: The name of the folder will show in the page url.
Choose a meaningful but short name, if possible.

. Add a description for the module to the file "partials/module-description.adoc" in your new module

. Add the new module's nav.adoc file to the antora.yml in the "doc" folder
+
TIP: The position in the list reflects the order of the modules in Antora's sidebar.

. Change the content of the module's nav.adoc file according to the in-module-navigation you want to have in the sidebar.

. Add the module structure to the plantuml file "structure.puml" in the examles of the project-guide module
//TODO: Automate this process step!

. Update the xref:structure/content_structure.adoc[] file accordingly

related::new-content-guide[]