
= Resolving Merge Conflicts
A merge conflict occurs when mutliple different changes (usually made by different users) are to be merged and some or all of the changes contradict each other. For example, if user A deletes a section in their copy and user B adds a new paragraph to it instead, the merging tool does not know whether to keep the section and add the changes made by user B or to delete it like user A did.


== Ways to avoid merge conflicts
One way of avoiding merge conflicts is to keep the TTL (time to live) of branches short. If the branch lives longer than expected, merge the master branch into your branch once in a while, this way you can solve the conflicts in your branch.

== Resolving Merge Conflicts in GitLab
Once you create a merge request git lab will tell you if there are merge conflicts. It can than lead you through the conflicting parts and lets you choose if your or the old content is to be merged.

Another possibility is to merge using VSCode, here a similar feature is included, in the end when done merging a merge commit is being created, which than can be pushed
