= ASAM project types
:description: Describes the different project types at ASAM for new members and interested parties.
:keywords: projects, type, asam, new-here-content

include::partial$_attributes.adoc[]
include::{abb}[]


__{asam}__ has four defined project types, which further characterize the work to be done within the projects. They are:

* <<Standard development project>>
* <<Implementation project>>
* <<Concept project>>
* <<Study project>>


They all have in common that the primary output of the project is a standard. The upper limit for subsidiary funding from __{asam}__ is 25% of the total required project budget.

== Standard development project
The core of __{asam}__ is to carry out standard development projects with the goal to create new standards and to update existing standards in accordance with the demands of ASAM members and market requirements. __{asam}__ defines four types of standard development projects, depending on the expected magnitude of changes to the standard:

* New standard development
* Major version development
* Minor version development
* Revision development

They all have in common that the primary output of the project is a standard.
The upper limit for subsidiary funding from __{asam}__ is 25% of the total required project budget.

For more information, see xref:standard-dev/standard_dev_types.adoc[].

== Implementation project
include::standardization:partial$project_types/project-type-implementation.adoc[tag=short]

== Concept project
include::standardization:partial$project_types/project-type-concept.adoc[tag=short]

== Study project
include::standardization:partial$project_types/project-type-study.adoc[tag=short]

related::project-types[]