= Standard tools - overview
:description: Links to the current contact page for ASAM Office members.
:keywords: tools, asam, new-here-content

include::partial$_attributes.adoc[]
include::{abb}[]

For the development of standards, __{asam}__ requires the use of some <<mandatory_tools_table,**mandatory tools**>> and recommends the use of others (<<recommended_tools_table,**recommended tools**>>).
Mandatory tools are tools that are required for specific tasks at __{asam}__.
They may not be mandatory for every user, since not all users need to perform the tasks where the tool is mandatory.
For more information on whether a tool is mandatory for your role, check out xref:role-specific:home.adoc[].

== Mandatory tools
Most <<mandatory_tools_table,**mandatory tools**>> are hosted by __{asam}__ and can be accessed through a browser directly without the need to install them locally.
However, some tools may be set up on the user's computer as well for easier access.

include::tooling:partial$list-of-tools.adoc[tag=mandatory]

== Recommended Tools
All <<recommended_tools_table,**recommended tools**>> are optional.
Each user may decide whether to use these tools, use alternatives, or just use the appropriate features in the webhosted counterpart in the mandatory tools.
However, __{asam}__ provides a set of instructions, how-tos, guides and other information on working with these recommended tools in ASAM projects that will not be available for alternative tools and methods.

include::tooling:partial$list-of-tools.adoc[tag = recommended]

== Further tools
For other tools typically used in ASAM projects, see https://www.asam.net/active-projects/resources/[window=_blank].

// related::tools-overview,mandatory,recommended[]