= Adding A Page
:description: Explains how to add a new page to the Project Guide and what to look out for.
:keywords: page,project-guide,new-content-guide, READYFORREVIEW
:page_reason: default page
:page_template_name: template-default-page.adoc
:page_template_alt_name: default page template
:page-aliases: adding_content/add-a-page.adoc

include::partial$standard_page_creation.adoc[]

TIP: You can exclude a page from Antora through its name.
If the filename starts with a dot ("."), Antora ignores it. +
If the filename starts with an underscore ("_"), Antora does not publish it but adds it to its internal content catalog (i.e. it is aware of it).

[NOTE]
====
This page describes all requirements each page in the project guide must fulfill.
However, certain types of pages have their own template.
See one of the pages for the specific templates listed under <<Pages>>.
====

// If you use a recurring image for similar artifacts, declare it as attribute in partials/_attributes.adoc and reference here.

IMPORTANT: Some pages or all pages in a certain module may use a custom convention, such as displaying an icon.
Look at similar files/pages in the same module and follow those conventions, where they add to the template above.

pages::[path=pages]
