@startuml
component compendium {
rectangle "compendium:nav.adoc" as f0_1
rectangle "compendium:docker/docker-for-asciidoc.adoc" as f0_2
rectangle "compendium:docker/standard-docker-config.adoc" as f0_3
rectangle "compendium:docker/starting-a-container.adoc" as f0_4
rectangle "compendium:docker/wsl.adoc" as f0_5
rectangle "compendium:git/cloning-repo-tutorial.adoc" as f0_6
rectangle "compendium:git/commit-guidelines.adoc" as f0_7
rectangle "compendium:git/git-actions.adoc" as f0_8
rectangle "compendium:git/git-terminology.adoc" as f0_9
rectangle "compendium:git/maintain-a-repo.adoc" as f0_10
rectangle "compendium:git/merge-requests.adoc" as f0_11
rectangle "compendium:git/merge.adoc" as f0_12
rectangle "compendium:git/Resolving-Merge-Conflicts.adoc" as f0_13
rectangle "compendium:git/review-code.adoc" as f0_14
rectangle "compendium:git/submodules.adoc" as f0_15
rectangle "compendium:git/Transitioning-to-a-new-workflow.adoc" as f0_16
rectangle "compendium:git/working-with-git.adoc" as f0_17
rectangle "compendium:git/write-a-feature.adoc" as f0_18
rectangle "compendium:gitlab/ASAM-Issue-and-MR-Labels.adoc" as f0_19
rectangle "compendium:gitlab/Branch-Naming-Conventions.adoc" as f0_20
rectangle "compendium:gitlab/Branching.adoc" as f0_21
rectangle "compendium:gitlab/cloning-a-repository.adoc" as f0_22
rectangle "compendium:gitlab/commit-guidelines.adoc" as f0_23
rectangle "compendium:gitlab/Forking.adoc" as f0_24
rectangle "compendium:gitlab/gitlab-ide-guide.adoc" as f0_25
rectangle "compendium:gitlab/gitlab-terminology.adoc" as f0_26
rectangle "compendium:powershell/cloning-a-repository.adoc" as f0_27
rectangle "compendium:powershell/powershell-basics.adoc" as f0_28
rectangle "compendium:powershell/run-docker.adoc" as f0_29
rectangle "compendium:sharepoint/links.adoc" as f0_30
rectangle "compendium:sharepoint/synchronizing-sharepoint-with-onedrive.adoc" as f0_31
rectangle "compendium:teams/email-notifications.adoc" as f0_32
rectangle "compendium:teams/meetings-in-teams.adoc" as f0_33
rectangle "compendium:teams/obtain-channel-email.adoc" as f0_34
rectangle "compendium:teams/polls-and-surveys.adoc" as f0_35
rectangle "compendium:teams/receive-notifications.adoc" as f0_36
rectangle "compendium:teams/teams-channel-file-structure.adoc" as f0_37
rectangle "compendium:vscode/Adding-Diagrams-To-VSCode.adoc" as f0_38
rectangle "compendium:vscode/cloning-a-repository.adoc" as f0_39
rectangle "compendium:vscode/recommended-vscode-extensions.adoc" as f0_40
rectangle "compendium:vscode/recommended-vscode-settings.adoc" as f0_41
rectangle "compendium:vscode/run-docker.adoc" as f0_42
rectangle "compendium:vscode/vscode-activity-bar.adoc" as f0_43
rectangle "compendium:vscode/vscode-command-palette.adoc" as f0_44
rectangle "compendium:vscode/VSCode-Git-Interaction.adoc" as f0_45
rectangle "compendium:vscode/vscode-install-extension.adoc" as f0_46
rectangle "compendium:vscode/vscode-interface.adoc" as f0_47
}
component getting-involved {
rectangle "getting-involved:nav.adoc" as f1_1
}
component getting-started {
rectangle "getting-started:nav.adoc" as f2_1
rectangle "getting-started:about-this-guide.adoc" as f2_2
rectangle "getting-started:main.adoc" as f2_3
rectangle "getting-started:new-here.adoc" as f2_4
rectangle "getting-started:quick-setup.adoc" as f2_5
rectangle "getting-started:about_guide/intentions-and-content.adoc" as f2_6
rectangle "getting-started:about_guide/using-this-guide.adoc" as f2_7
rectangle "getting-started:about_guide/working-on-the-guide.adoc" as f2_8
rectangle "getting-started:new_here/asam-contacts.adoc" as f2_9
rectangle "getting-started:new_here/current-projects.adoc" as f2_10
rectangle "getting-started:new_here/how-asam-works.adoc" as f2_11
rectangle "getting-started:new_here/processes-and-workflows-overview.adoc" as f2_12
rectangle "getting-started:new_here/roles-overview.adoc" as f2_13
rectangle "getting-started:new_here/tools-overview.adoc" as f2_14
rectangle "getting-started:quick_setup/docker-standard.adoc" as f2_15
rectangle "getting-started:quick_setup/git-standard.adoc" as f2_16
rectangle "getting-started:quick_setup/microsoft-teams-standard.adoc" as f2_17
rectangle "getting-started:quick_setup/sharepoint-standard.adoc" as f2_18
rectangle "getting-started:quick_setup/vscode-standard.adoc" as f2_19
}
component project-guide {
rectangle "project-guide:nav.adoc" as f3_1
rectangle "project-guide:add-a-page.adoc" as f3_2
rectangle "project-guide:add-a-partial.adoc" as f3_3
rectangle "project-guide:add-new-module.adoc" as f3_4
rectangle "project-guide:attachments.adoc" as f3_5
rectangle "project-guide:examples.adoc" as f3_6
rectangle "project-guide:images.adoc" as f3_7
rectangle "project-guide:pages-vs-partials.adoc" as f3_8
}
component role-specific {
rectangle "role-specific:nav.adoc" as f4_1
rectangle "role-specific:ASAM-Project-Roles.adoc" as f4_2
rectangle "role-specific:home.adoc" as f4_3
}
component ROOT {
rectangle "ROOT:1nav.adoc" as f5_1
rectangle "ROOT:nav.adoc" as f5_2
rectangle "ROOT:home copy.adoc" as f5_3
rectangle "ROOT:home.adoc" as f5_4
rectangle "ROOT:linking-test.adoc" as f5_5
rectangle "ROOT:antora/Build-Antora-Locally.adoc" as f5_6
rectangle "ROOT:antora/Content-Structure.adoc" as f5_7
rectangle "ROOT:guides/Accessing_Compiled_Artifacts.adoc" as f5_8
rectangle "ROOT:guides/Meeting-Guidelines.adoc" as f5_9
rectangle "ROOT:guides/Platforms.adoc" as f5_10
rectangle "ROOT:guides/ProjectGuidelines.adoc" as f5_11
rectangle "ROOT:guides/WhatIsYaml.adoc" as f5_12
rectangle "ROOT:guides/Workflow.adoc" as f5_13
rectangle "ROOT:guides/WritingGuidelines.adoc" as f5_14
rectangle "ROOT:implementers-forum/Feedback-Guide.adoc" as f5_15
rectangle "ROOT:implementers-forum/Scenario-Writers-Guide.adoc" as f5_16
rectangle "ROOT:open-source/ASAM-DCO.adoc" as f5_17
rectangle "ROOT:writing_guidelines/AsciiDoc-Guide.adoc" as f5_18
rectangle "ROOT:writing_guidelines/coding_style_guide.adoc" as f5_19
rectangle "ROOT:writing_guidelines/plantuml_documentation_guide.adoc" as f5_20
rectangle "ROOT:writing_guidelines/writing_guide.adoc" as f5_21
}
component standardization {
rectangle "standardization:nav.adoc" as f6_1
rectangle "standardization:asam-development-process.adoc" as f6_2
rectangle "standardization:development-phase.adoc" as f6_3
rectangle "standardization:home.adoc" as f6_4
rectangle "standardization:project-setup.adoc" as f6_5
rectangle "standardization:project-types.adoc" as f6_6
rectangle "standardization:proposal-phase.adoc" as f6_7
rectangle "standardization:release-phase.adoc" as f6_8
rectangle "standardization:review-phase.adoc" as f6_9
}
component tasks {
rectangle "tasks:nav.adoc" as f7_1
}
component tooling {
rectangle "tooling:nav.adoc" as f8_1
rectangle "tooling:calendar.adoc" as f8_2
rectangle "tooling:docker.adoc" as f8_3
rectangle "tooling:drawio.adoc" as f8_4
rectangle "tooling:git.adoc" as f8_5
rectangle "tooling:gitlab.adoc" as f8_6
rectangle "tooling:overview.adoc" as f8_7
rectangle "tooling:teams-and-sharepoint.adoc" as f8_8
rectangle "tooling:vscode.adoc" as f8_9
rectangle "tooling:working-without-software-installation.adoc" as f8_10
rectangle "tooling:calendar/calendar-best-practices.adoc" as f8_11
rectangle "tooling:calendar/calendar-setup.adoc" as f8_12
rectangle "tooling:docker/docker-best-practices.adoc" as f8_13
rectangle "tooling:docker/docker-guides.adoc" as f8_14
rectangle "tooling:docker/docker-setup.adoc" as f8_15
rectangle "tooling:drawio/drawio-setup.adoc" as f8_16
rectangle "tooling:git/git-best-practices.adoc" as f8_17
rectangle "tooling:git/git-guides.adoc" as f8_18
rectangle "tooling:git/git-setup.adoc" as f8_19
rectangle "tooling:gitlab/gitlab-guides.adoc" as f8_20
rectangle "tooling:gitlab/gitlab-setup.adoc" as f8_21
rectangle "tooling:teams_and_sharepoint/teams-and-sharepoint-best-practices.adoc" as f8_22
rectangle "tooling:teams_and_sharepoint/teams-and-sharepoint-guides.adoc" as f8_23
rectangle "tooling:teams_and_sharepoint/teams-and-sharepoint-setup.adoc" as f8_24
rectangle "tooling:vscode/vscode-guides.adoc" as f8_25
rectangle "tooling:vscode/vscode-setup.adoc" as f8_26
}

f8_3 -left-> f0_2
f2_3 -left-> f2_1
f2_4 -left-> f2_1
f2_2 -left-> f2_1
f2_5 -left-> f2_1
f2_4 -left-> f2_3
f2_2 -> f2_3
f2_5 -left-> f2_3
f3_4 -left-> f3_1
f6_4 -left-> f6_1
f6_2 -left-> f6_1
f6_7 -left-> f6_1
f6_6 -left-> f6_1
f6_5 -left-> f6_1
f6_3 -left-> f6_1
f6_9 -left-> f6_1
f6_8 -left-> f6_1
f8_7 -left-> f8_1
f8_10 -left-> f8_1
f8_6 -left-> f8_1
f8_2 -left-> f8_1
f8_8 -left-> f8_1
f8_9 -left-> f8_1
f8_5 -left-> f8_1
f8_4 -left-> f8_1
f8_3 -left-> f8_1
f8_6 -left-> f8_5
f8_5 -> f8_6
f8_10 -> f8_7
f8_6 -> f8_9
f8_5 -left-> f8_10
f8_9 -left-> f8_16
f8_9 -left-> f8_19

cloud "https://code.asam.net/common/style-resources"  as u1
cloud "https://docs.microsoft.com/en-us/windows/wsl/about"  as u2
cloud "https://help.github.com/articles/using-pull-requests/"  as u3
cloud "http://stackoverflow.com/a/17819027"  as u4
cloud "https://tortoisegit.org/"  as u5
cloud "https://code.asam.net"  as u6
cloud "http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html"  as u7
cloud "https://help.github.com/articles/about-git-rebase/"  as u8
cloud "https://docs.gitlab.com/ee/user/project/repository/web_editor.html"  as u9
cloud "https://docs.gitlab.com/ee/user/project/web_ide/#open-the-web-ide"  as u10
cloud "https://docs.gitlab.com/ee/user/project/web_ide/"  as u11
cloud "https://upload.wikimedia.org/wikipedia/commons/2/2f/PowerShell_5.0_icon.png"  as u12
cloud "https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7.1"  as u13
cloud "https://asamev.sharepoint.com/sites/asamopensimulationinterface/Freigegebene%20Dokumente/Forms/AllItems.aspx"  as u14
cloud "https://asamev.sharepoint.com/sites/openscenario/Freigegebene%20Dokumente/Forms/AllItems.aspx"  as u15
cloud "https://asamev.sharepoint.com/sites/openscenario2/Freigegebene%20Dokumente/Forms/AllItems.aspx"  as u16
cloud "https://asamev.sharepoint.com/sites/openxontology/Freigegebene%20Dokumente/Forms/AllItems.aspx"  as u17
cloud "https://www.doodle.com"  as u18
cloud "https://support.microsoft.com/en-us/office/manage-notifications-in-teams-1cc31834-5fe5-412b-8edb-43fecc78413d"  as u19
cloud "https://kroki.io/examples.html"  as u20
cloud "https://code.visualstudio.com/docs/editor/versioncontrol#_git-support"  as u21
cloud "https://cdn.icon-icons.com/icons2/2415/PNG/512/gitlab_original_logo_icon_146503.png"  as u22
cloud "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Git_icon.svg/240px-Git_icon.svg.png"  as u23
cloud "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/240px-Visual_Studio_Code_1.35_icon.svg.png"  as u24
cloud "https://dashboard.snapcraft.io/site_media/appmedia/2019/08/android-chrome-512x512.png"  as u25
cloud "https://github.com/Mogztter/antora-lunr"  as u26
cloud "https://github.com/asam-ev"  as u27
cloud "https://code.asam.net/simulation/standard/openscenario-2.0/-/wikis/docs/git/Transitioning-to-a-new-workflow"  as u28
cloud "https://code.asam.net/help/user/project/quick_actions"  as u29
cloud "https://docs.gitlab.com/ee/user/discussions/#starting-a-review"  as u30
cloud "https://code.asam.net/simulation/standard/openscenario-2.0/-/boards/66"  as u31
cloud "https://code.asam.net/simulation/standard/openscenario-2.0/-/issues?label_name%5B%5D=ScenarioDescription"  as u32
cloud "https://code.asam.net/simulation/standard/openscenario-2.0/-/wikis/Contact-Persons-from-OSC2-Development-Project"  as u33
cloud "https://code.asam.net/simulation/standard/openscenario-2.0/-/issues?label_name%5B%5D=GeneralFeedback"  as u34
cloud "https://code.asam.net/simulation/standard/openscenario-2.0/-/issues/245"  as u35
cloud "https://code.asam.net/simulation/standard/openscenario-2.0/-/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D=#"  as u36
cloud "https://code.asam.net/simulation/standard/openscenario-2.0/-/jobs/artifacts/master/raw/Language/ASAM_OpenSCENARIO_BS-1-6_Language-Reference-Manual_V2-0-0.html?job=draft"  as u37
cloud "https://asciidoc.org/"  as u38
cloud "https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/"  as u39
cloud "https://asciidoctor.org/docs/user-manual/"  as u40
cloud "https://www.url.com"  as u41
cloud "https://asciidoctor.org/docs/user-manual/#tables"  as u42
cloud "https://asciidoctor.org/docs/user-manual/#include-directive"  as u43
cloud "https://www.python.org/dev/peps/pep-0008/"  as u44
cloud "https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/"  as u45
cloud "https://code.asam.net/simulation/resources/-/blob/master/asciidoc_tutorial/asciidoc_tutorial.adoc"  as u46
cloud "https://code.asam.net/simulation/standard/openscenario-2.0/-/tree/master/Documentation/etc/templates"  as u47
cloud "https://code.asam.net/simulation/standard/openscenario-2.0/-/blob/master/Documentation/etc/guides/coding_style_guide.adoc"  as u48
cloud "https://code.asam.net/simulation/standard/openscenario-2.0/-/blob/master/Documentation/etc/guides/plantuml_documentation_guide.adoc"  as u49
cloud "https://code.asam.net/simulation/standard/openscenario-2.0/-/wikis/docs/general_guidelines/Workflow"  as u50
cloud "https://upload.wikimedia.org/wikipedia/commons/d/df/Microsoft_Office_Outlook_%282018%E2%80%93present%29.svg"  as u51
cloud "https://upload.wikimedia.org/wikipedia/commons/a/a5/Google_Calendar_icon_%282020%29.svg"  as u52
cloud "https://docs.docker.com/get-started/"  as u53
cloud "https://dockerlabs.collabnix.com/beginners/components/container-vs-image.html"  as u54
cloud "https://docs.docker.com/desktop/windows/install/#system-requirements"  as u55
cloud "https://docs.docker.com/desktop/windows/install/"  as u56
cloud "https://docs.docker.com/engine/install/binaries/"  as u57
cloud "https://www.docker.com/blog/updating-product-subscriptions/"  as u58
cloud "https://www.git-tower.com/learn/git/faq/git-squash"  as u59
cloud "https://code.asam.net/-/profile"  as u60
cloud "https://code.asam.net/profile/keys"  as u61

f0_2 .up.>> u1
f0_5 .up.>> u2
f0_10 .up.>> u3
f0_12 .up.>> u4
f0_15 .up.>> u1
f0_15 .up.>> u5
f0_15 .up.>> u6
f0_18 .up.>> u7
f0_18 .up.>> u8
f0_18 .up.>> u3
f0_25 .up.>> u9
f0_25 .up.>> u10
f0_25 .up.>> u11
f0_26 .up.>> u9
f0_26 .up.>> u10
f0_26 .up.>> u11
f0_28 .up.>> u12
f0_28 .up.>> u13
f0_30 .up.>> u14
f0_30 .up.>> u15
f0_30 .up.>> u16
f0_30 .up.>> u17
f0_35 .up.>> u18
f0_36 .up.>> u19
f0_38 .up.>> u20
f0_45 .up.>> u21
f4_3 .up.>> u22
f4_3 .up.>> u23
f4_3 .up.>> u24
f4_3 .up.>> u25
f5_3 .up.>> u22
f5_3 .up.>> u23
f5_3 .up.>> u24
f5_3 .up.>> u25
f5_6 .up.>> u26
f5_10 .up.>> u6
f5_10 .up.>> u27
f5_13 .up.>> u28
f5_13 .up.>> u29
f5_13 .up.>> u30
f5_15 .up.>> u31
f5_15 .up.>> u32
f5_15 .up.>> u33
f5_15 .up.>> u34
f5_15 .up.>> u35
f5_16 .up.>> u36
f5_16 .up.>> u37
f5_16 .up.>> u33
f5_18 .up.>> u38
f5_18 .up.>> u39
f5_18 .up.>> u40
f5_18 .up.>> u41
f5_18 .up.>> u42
f5_18 .up.>> u43
f5_19 .up.>> u44
f5_21 .up.>> u45
f5_21 .up.>> u46
f5_21 .up.>> u47
f5_21 .up.>> u48
f5_21 .up.>> u49
f5_21 .up.>> u50
f8_12 .up.>> u51
f8_12 .up.>> u52
f8_13 .up.>> u53
f8_13 .up.>> u54
f8_15 .up.>> u55
f8_15 .up.>> u56
f8_15 .up.>> u57
f8_15 .up.>> u58
f8_17 .up.>> u8
f8_17 .up.>> u59
f8_17 .up.>> u7
f8_19 .up.>> u60
f8_19 .up.>> u61
@enduml