= Participating In A Project
:description:
:keywords:

include::partial$_attributes.adoc[]
include::{abb}[]


== The Development Phase
The description of the ASAM standard development process in this section contains all formal process steps to develop an ASAM standard. +
The process steps are mandatory for the development of new standards and the development of a major version of an existing ASAM standard.
For all other project types, some of the process steps are optional (see xref:concepts:project_types.adoc[]).

This process description focuses on the ideal and best-case course of an ASAM project.
Real projects may have iterations, loops and interventions by the __{tsc}__, Office, or Board of Directors. +
Project groups may decide to re-start a project with an updated project proposal, upgrade to a higher release level, or to prematurely end the project.
While those events can occur and need to be appropriately managed, they are out-of-scope for this Project Guide.

image::compendium:asam/development_phase.drawio.svg[title=The development phase in detail]




TODO