= Ideation Phase
:description: Describes how to enter a new idea into the ideation process.
:keywords: ideation, idea

include::partial$_attributes.adoc[]
include::{abb}[]

====
[cols="1,5", frame=none, grid = rows]
|===
h|Involved roles
a| * {role-standard-user} -> {role-idea-giver}
* {role-gtm}
* {role-member}

h| Project phase
| image:compendium:asam/project_lifecycle-ideation.svg[]

|===
====

== Getting Started Immediately

[horizontal]
xref:ideation/enter_new_idea.adoc[]:: Start here to learn how you can enter an idea at ASAM.
xref:ideation/developing_an_idea.adoc[]:: Start here if you want to further develop an idea you previously entered.
xref:ideation/raising_interest.adoc[]:: Start here for tips and tricks on finding enough project participants.

== Process Overview

[horizontal]
Info page:: https://www.asam.net/active-projects/ideation/how-it-works/[window=_blank]

The convergence of the automotive markets with new trends in digitalization, autonomous driving, alternative propulsion, and vehicle as a service as enabled by new IT business models provides many new technical concepts that can be standardized in ASAM.

Standardization requires three components:

* A technical concept
* A market need for the standard
* Passionate, technical experts who convene at regular intervals to define the requirements and the implementation

To make sure that these requirements are met, ASAM has launched this https://www.asam.net/active-projects/ideation/how-it-works/[ideation platform^]. +
Technical experts from all over the globe can post concepts and ideas, receive feedback, and drive new standardization topics.

image::compendium:asam/ideation_phase-ideation_phase.svg[title="The ideation phase in detail"]


