= How to get involved
:description: Landing page for information on how to get involved in ASAM projects.
:keywords: landing_page,get-involved, TODO
:page-aliases: home.adoc

include::partial$_attributes.adoc[]
include::{abb}[]
include::ROOT:partial$_attributes.adoc[]

{getting-involved-icon}

include::partial$module-description.adoc[]

You want to **propose an idea**, **join a proposal** or **develop a new standard** at __{asam}__?
The pages in this module got you covered.
Alternatively, you may also https://www.asam.net/contact/[contact the ASAM office^] directly.

Some of the following pages are mainly intended for particular xref:getting-started:roles-overview.adoc[roles at ASAM].
These pages have the relevant role labels at the top.
However, the labels do not act as prerequisits or requirements.
If restrictions apply, they are listed separately.

[IMPORTANT]
====
For some activities, an ASAM membership is required. +
**If you consider becoming an ASAM member to join a project, see https://www.asam.net/about-asam/join-asam/[join ASAM on the ASAM website^].**
====

== Content

// idea: Add image that guides through the process with a timeline
// TODO: Wait on feedback from restructuring

include::../nav.adoc[lines=2..-1]