= Review a standard (public)
:description: Describes how to review a standard.
:keywords: review, TODO

include::partial$_attributes.adoc[]
include::{abb}[]

{role-standard-user}

// - internal reviews: within group --> discuss and decide in group
// - ASAM public reviews: review with ASAM members -->
// - public reviews: public and open review -->

== Context
Standards creation requires constant reviewing of its content.
Some projects receive a public review phase.
In these, any person can participate without having to be an ASAM member.

If a document or documents enter the Public Review phase, it is announced through the https://www.asam.net/newsletter/[newsletter^] and the https://www.asam.net/active-projects/public-review/[ASAM website^].

This review occurs at the end of a standardization project.

This description is intended for all people interested in giving feedback for such a review document, independent of ASAM membership status.

== Result
Comprehensive and comprehensible feedback has been submitted to the project group on the review document(s).

== Prerequisites
* Documents must be in public review

== How
. Access the "Public Review" page (through the website or the newsletter)
. Select the standard you would like to review to be forwarded to its review page
.. If not logged in, a popup window will appear for you to log into your ASAM account first
. Read through the document(s) carefully
. Provide feedback on these through the integrated feedback tools

ASAM uses the following feedback tools:
include::tooling:partial$review_tools.adoc[]

// == Troubleshooting / Known Issues
