= Microsoft Teams and Sharepoint
:description: A summary page describing what MS Teams and Sharepoint are and where to find related information, guides etc.
:keywords: teams,sharepoint,summary,tool,mandatory,TODO

include::partial$_attributes.adoc[]
include::{abb}[]


{sharepoint-icon}
{teams-icon}


Microsoft (MS) Teams is used to communicate and exchange documents **without direct impact on the standards** within project groups.
Different groups and topics are gathered under different channels.
Here, users can chat with each other and share files directly. +
Sharepoint is a Microsoft service that is used in the background by Teams to manage files.
It can be accessed directly or through Teams, which is why all files that have been added either way can be retrieved through both tools.


* Each channel in Teams has a "Chat" tab for chatting & a "Files" tab to share files.
** If you need another Teams channel, contact mailto:benjamin.engel@asam.net[Benjamin Engel]!
* These file tabs can also be found directly in Sharepoint (sign in with your microsoft account).

IMPORTANT: Project files such as chapters, specifications, or images intended for use in the standard are to be handled through GitLab instead! See xref:compendium:guides/standard_workflow.adoc[] for more information.


== MS Teams at ASAM
//TODO

== MS Sharepoint at ASAM
//TODO

== Content


[cols="^1h,4",frame=none, grid=rows, stripes=hover]
|===

|xref:teams_and_sharepoint/teams-and-sharepoint-setup.adoc[image:{setup-image}[width=120,title="Teams And Sharepoint Setup"]]
|Teams And Sharepoint Setup

|xref:teams_and_sharepoint/teams-and-sharepoint-guides.adoc[image:{guide-image}[width=120,title="Teams And Sharepoint Guides"]]
|Teams And Sharepoint Guides

|===

related::sharepoint[]
