= Pulling A Submodule
:description: Describes how a submodule can be pulled.
:keywords: git,gitlab,submodule,pull
:page-partial:

include::compendium:partial$_attributes.adoc[]

Pulling a submodule can currently only be done through a terminal window.

TIP: If you have https://tortoisegit.org/[TortoiseGit^] installed, you can also do this through the TortoiseGit UI. See the https://tortoisegit.org/docs/tortoisegit/tgit-dug-submodules.html[TortoiseGit Tutorial on Submodules^] for more information.

. To pull a submodule, you need to open a terminal (git bash or xref:../tool-specific/PowerShell-Basics.adoc[Windows Powershell]) in the folder of your git repository.
. Type the one of the following commands and confirm with Enter
.. **Updating Submodules after checking out repository** (first time):
+
[source, git]
----
git submodule update --recursive --init
----
+
.. **Regular updating of Submodules**:
+
[source, git]
----
git submodule update --recursive
----
+
NOTE: After you have initialized your submodules for the first time, they will also show up in your Git window in VSCode where you can update them directly from VSCode.

TIP: You can even leave out the `--recursive` part if you know that your submodules do not contain submodules themselves.

related::submodules[]
