= ASAM Project Guide
:description: The main wiki landing page for the ASAM Wiki and Project Guide.
:keywords: main, home, start

include::partial$_attributes.adoc[]

Welcome to the **ASAM Project Guide**!

This guide provides an introduction to new members on ASAM in general and its most central topics, gives an overview on how to get involved and provides role-specific information for working at ASAM and in ASAM projects.
In addition to that, it also contains a full explanation on each and every process and workflow applied in ASAM projects, contains guides on suggested tools as well as a compendium on specific tasks and topics.
Lastly, you can also find information and guides on how to participate in improving this project guide.


== Quick Access
[cols="1,4"]
|===

|{getting-started-icon-norole}
|
include::getting-started:partial$module-description.adoc[]

|{getting-involved-icon-norole}
|
include::getting-involved:partial$module-description.adoc[]

|{role-specific-icon-norole}
|
include::role-specific:partial$module-description.adoc[]

|{standardization-icon-norole}
|
include::standardization:partial$module-description.adoc[]

|{compendium-icon-norole}
|
include::compendium:partial$module-description.adoc[]

|{tools-icon-norole}
|
include::tooling:partial$module-description.adoc[]

|{project-guide-icon-norole}
|
include::project-guide:partial$module-description.adoc[]

|===
