= Standard Docker Compose YAML

== Why Use Docker?

A project's final specification document is created as HTML file. However, having to run it through the pipeline every time before being able to see the final result after having made changes is neither efficient nor
To render a project's documentation without having to upload it, use Docker Compose with a correctly defined docker-compose.yml file.

You can download the standard docker-compose.yml link:{attachmentsdir}/docker-compose.yml[here].

**See also**: <<../general_guidelines/WhatIsYaml.adoc#,What is YAML/yml?>>

== Standard Docker-Compose Instructions

// TODO: Link to the attachment file!

. Create a new `docker-compose.yml` file in the root directory of the project.
. Add the following content to the created file:
+
[source,yaml]
----
version: "2"

services:
  asciidoctor:
    image: asciidoctor/docker-asciidoctor
    volumes:
      - .:/documents
    entrypoint: asciidoctor --failure-level WARN -r asciidoctor-diagram -a mathjax -r asciidoctor-bibtex --trace standard/main.adoc -o HTML_standard_local_build.html

----
+
. Run docker-compose with `docker-compose run asciidoctor`

NOTE: Usually, the only adaption that may be required is to change the input file (`standard/main.adoc`).All the other configuration required is in the docker-compose.yml.

TIP: It is also possible to include the running of scripts into this (e.g. adoc2LOFT)

=== Typical Configuration Options

Each project may have slightly different requirements, and at different stages of the project different features are available or not. To accommodate for that, the docker-compose.yml can be configured with options in the `entrypoint`.

=== Asciidoctor Diagram

If Asciidoctor Diagram is to be used, make sure that the option `-r asciidoctor-diagram` is set.

=== Mathjax

Mathjax is a JavaScript display engine intended for displaying mathmatical expressions in browsers. This can be activated by adding `-a mathjax` to the entrypoint.

=== Asciidoctor Bibtex

If Asciidoctor Bibtex is to be used, make sure that the option `-r asciidoctor-bibtex` is set.

NOTE: The use of asciidoctor-bibtex requires that a bibtex configuration for the project is present. If the project does not have such a configuration (yet), remove this option. Otherwise, the container will fail to create any output!

=== Single Input File

You can define the input file by using `path-to-file/filename.format`. In the standard version above, this is set to `standard/main.adoc`. Replace this, if necessary.

=== Multiple Input Files

If you want to process more than one file in one go, you can replace `path-to-file`, `filename` or both with `*`, so that it searches through all paths, files or both respectively.

=== Output File

You can define the output file by using `-o path-to-file/filename.format`. By default, HTML is created, so use ".html" as your format. In the standard version above, this is set to `HTML_standard_local_build.html`.

=== Output path

If you only want to specifiy the output path but leave the naming convention of the input files, use the option `-D path` instead of

== See Also

- <<../writing_guidelines/Docker-For-Asciidoc.adoc#,Using Docker for Asciidoctor>>
- <<DockerGuide.adoc#,Docker Guide>>
- <<../general_guidelines/Getting-Docker.adoc#,Docker Setup>>
