
== Whom To Invite?
- While the project is still in the early phase, people will likely be moving around in groups
- Send the invite to those emails registered for the group; additionally, CC the following:
  - The project lead and the ASAM representative.
  - The shared OpenX Calendar, openx@asam.net.
  - The Teams channel email; this will post the meeting in the channel for all to see. See <<ObtainMailInTeams.adoc#,Obtaining A Teams Channel Email>>.

>To find the list of people registered for your group or WP, see the WP signup list. Its location is described <<docs/project_guidelines/Microsoft-Teams-and-Sharepoint#user-content-teams-channels-file-structure#,here>>.

== Setting Up A Meeting:
- If you have a Teams license, you can setup a Teams meeting directly. See <<docs/project_guidelines/Microsoft-Teams-and-Sharepoint#user-content-setting-up-a-meeting#,setting up a Teams meeting>>.
- Otherwise, feel free to use whatever solution you or your company normally use.
- If all else fails, send the details to your ASAM rep. and they will assist (either Teams or Zoom).
