[[top-submodules]]
= Git submodules usage
:description: Describes how to use submodules in git.
:keywords: git, submodule

include::compendium:partial$_attributes.adoc[]


{asam} uses submodules to include reuse resources in all repositories, e.g. document style configuration.
The submodule has to be added to the repository during setup of the repository.

== Adding a submodule

To add a submodule to a repository, follow this steps. All examples are shown using the https://code.asam.net/common/style-resources[ASAM asciidoc-resources repository]. Replace as needed.

[source,console]
----
> git submodule add git@code.asam.net:common/style-resources.git // <1>
// Then edit .gitmodule for relative pathing
> git add .gitmodules
----


=== Edit .gitmodule for relative pathing


[source,console]
----
> cat .gitmodules
[submodule "asciidoc-resources"]
        path = asciidoc-resources
        url = git@code.asam.net:common/style-resources.git // <1>
// [change path using editor of choice]
> cat .gitmodules
[submodule "asciidoc-resources"]
        path = asciidoc-resources
        url = ../../common/asciidoc-resources.git // <2>
----
<1> absolute path to repo
<2> relative path to repo, when parent repo is also on https://code.asam.net. Note that this has so represent the internal repository structure of code.asam.net.

After that `> git commit` & `> git push`.



[NOTE]
====
When setting up a repository NOT on code.asam.net (e.g. Github for OSI)::
. use the https adress of the repository.
`+git submodule add https://code.asam.net/common/style-resources.git+`

. Do **NOT** <<Edit .gitmodule for relative pathing>>!
====



== Using a submodule

A submodule is not autoatically checkout with chechout of the parent directory. To checkout the submodule use:

[source,console]
----
> git submodule update --init
----


== Settings a submodule to a certain tag

When a certain version of the submodule is needed, go into the submodule and checkout the needed version.

[source,console]
----
> cd asciidoc-resources
> git checkout [tag]
> cd ..
> git add asciidoc-resources
----

After that `> git commit` & `> git push`.



== Deleting a submodule

To delete a submodule do:

[source,console]
----
> git rm .gitmodules // <1>
> git rm asciidoc-resources
----
<1> This deletes all submodules in a repository. If there is another submodule that should be kept, just delete the corresponding lines from the `.gitmodules`.


After that `> git commit` & `> git push`.


