
= How To Use Docker For Asciidoctor
:docker-download: https://docs.docker.com/get-docker/

== Wait, What Is Docker?

Docker is a tool for hosting and accessing so-called containers. For Asciidoc, docker can be used to run a pre-configured asciidoctor setup for creating html output locally. This removes the need to upload adoc files and use the build pipeline for every change you want to see. It also means you do not have to install and configure Asciidoctor first since this is already done in the pre-configured Docker image.

If you do not have Docker installed, check out the xref:general_guidelines/Getting-Docker.adoc[guide on getting docker] before continuing.

If your project is currently missing the docker-compose.yml, see these xref:tool-specific/StandardDockerConfig.adoc[instructions] on how to set it up.

== Setup

Setup for docker and adding the docker-compose.yml to a project is described on the linked pages:

Tooling:: xref:general_guidelines/Getting-Docker.adoc[Guide on getting docker]

Project:: xref:tool-specific/StandardDockerConfig.adoc[Standard docker-compose.yml]

== Using Docker For Asciidoc

The xref:tool-specific/Recommended-VSCode/Extensions.adoc#AsciiDoc[VSCode extension for Asciidoc] provides a decent preview. However, some styling and content will not look exactly as in the final result. If the layout and final look is important, you should create the HTMl output from the adoc files by using the asciidoctor docker container (configured in the xref:tool-specific/StandardDockerConfig.adoc[standard docker-compose.yml]).

For information on how to execute docker-compose, see the xref:tool-specific/DockerGuide.adoc[Docker Guide].

IMPORTANT: Make sure to execute the asciidoctor service in the container as it may contain more than one service.

After running docker-compose, one or more html files will have been created depending on your docker-compose.yml. If you use the standard configuration, the created file will be named "HTML_standard_local_build.html" and can be found in the same folder as your "docker-compose.yml" file.

TIP: For ensuring compliance with the ASAM style guidelines, make sure the project contains the relevant link:https://code.asam.net/common/style-resources[style resources] and that they are included as "preamble.adoc" in the file you are processing with asciidoctor.

== See Also
* xref:general_guidelines/Getting-Docker.adoc[Getting Docker]
* xref:tool-specific/DockerGuide.adoc[General Docker guide]
* xref:general_guidelines/WritingGuidelines.adoc[Writing guidelines]
* xref:AsciiDoc-Guide.adoc[AsciiDoc guide]
* xref:tool-specific/StandardDockerConfig.adoc[Setup of standard docker-compose.yml]
