= Standard manager
:description: Describes a standard manager from ASAM project view.
:keywords: role

//tag::default[]
include::compendium:partial$_attributes.adoc[]
include::{abb}[]

{role-standard-manager}

//end::default[]

== Issue resolution
//tag::issue_resolution[]
Each ASAM standard has an appointed Standard Manager.
They manage the issue resolu-tion process for the standard that they are appointed to.
His primary goals are to resolve known issues of the standard, carrying out all work necessary for implementing the fix and to keep the work load for the members of the Standard Expert Group (see next sub-chapter) as low as possible.
His primary tasks are:

* Handling of support requests on 2nd-level.
* Handling and monitoring of change requests (CRs).
* Maintain the public list of known issues (LOKI).
* Create proposals to resolve those CRs, which are categorized as an issue.
* Organize and carry out Standard Expert Group meetings.
* Create revisions of the standard.
* Obtain technical and public releases of the revised standard.

By default, the Standard Manager is a staff member of the ASAM Office.
ASAM members can voluntarily take over the role of Standard Manager for a standard.
If there are no volun-teers available among ASAM members and if the ASAM Office staff is either not qualified or the volume of work would be too high, then the office shall appoint a paid service provider for the job.
The minimum tenure for the Standard Manager shall be one year.
//end::issue_resolution[]