How-To: Become Project Lead
:description: Describes the steps to becoming the project lead of a project after having handed in the candidacy.
:keywords: project-lead

include::compendium:partial$_attributes.adoc[]

//tag::body[]

[cols="1,5"]
|===
h|Target Role
|{role-project-lead}

h|Eligible
|{role-wg-member}

h|Requirements
a|* Commitment to project declared
* xref:getting-involved:proposal/submit_candidacy.adoc[Candidacy submitted]

h|Motivation
| To lead the direction of activities of a project.

h|When
| xref:proposal_phase.adoc#_the_proposal_phase[Proposal phase]

h|Summary
| The project responsible and main content coordinator of a project.

h|Tasks
a| * Coordinating project activities
* Prioritizing project activities
* Synchronization with Working Group Leads

|===

IMPORTANT: To become the Project Lead of a project, you must first xref:getting-involved:proposal/submit_candidacy.adoc[**submit your candidacy**] in the Proposal phase.


== Context
TODO

== Responsibilities
The Workgroup Lead is responsible for

*

== Prerequisites
* Each project lead must fulfill a list of requirements.
See the xref:compendium:ASAM/roles/project_lead_training.adoc[] for more information on the training for becoming a project lead.

== When
The Project Lead is elected at the beginning of a project. +
In rare cases, a new Project Lead can be elected during a project if the previous one resigns.

== How
TODO

== Frequently Asked Questions
TODO


See also: xref:role-specific:project-lead.adoc[].
//end::body[]