= Documentation As Code
:description: Gives an introduction for the concept of documentation-as-code.
:keywords: concept

include::partial$_attributes.adoc[]
include::{abb}[]


The concept of Documentation as Code (or Doc as Code) refers to using the same tools for documentation as for writing (software) code. +
Typically, this involves

* using <<Issue Tracking,issue tracking>>
* having a <<Version Control System, version control system>> (e.g. Git)
* using <<Plain Text Markup,plain text markup>> for content (e.g. AsciiDoc)
* doing <<Reviews,(code) reviews>>
* <<Process Automation,automating >>steps in the (code/content) generation.

All standards in the ASAM Simulation domain follow this concept.
Different projects may use different tools or versions of the same tools, but the central ideas stay the same.

== Issue Tracking
Issues are open topics and found bugs collected in a central system. +
ASAM uses xref:tooling:gitlab.adoc[] (self-hosted) and xref:tooling:github.adoc[] (cloud) for different projects.

== Version Control System
A version control system keeps track of changes in a file system. +
ASAM uses xref:tooling:git.adoc[] and some remote solution (either xref:tooling:gitlab.adoc[] or xref:tooling:github.adoc[]).

== Plain Text Markup
A plain text markup language that separates the writing from the publishing.
This means that the content (the "writing") and its styling and layout (the "publishing") are not defined simultaneously (like in Microsoft Word) but applied through specified rules.
Typical examples are the languages Markdown, LaTeX, and AsciiDoc. +
ASAM uses https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc^] for its documents.

== Reviews
TODO

== Process Automation
ASAM projects typically automate the following steps:

* Convert AsciiDoc files to html and pdf using https://asciidoctor.org/[Asciidoctor^]
* https://en.wikipedia.org/wiki/Lint_(software)[Linting^] and testing documents for rules defined in the xref:compendium:writing_guidelines/editorial_guide.adoc[] and returning found errors
* Publishing results as pipeline artifacts for downloads or distribution
* Running project-specific scripts for additional features, such as converting uml diagrams to AsciiDoc files


For more information on the standard ASAM pipeline, see xref:pipeline_details.adoc[].