= Adding A Page
:description: Explains how to add a new page to the Project Guide and what to look out for.
:keywords: page,project-guide,new-content-guide
:page-partial:

include::partial$_attributes.adoc[]
include::{abb}[]

// If you use a recurring image for similar artifacts, declare it as attribute in partials/_attributes.adoc and reference here.

== Context
To add a new page or make an existing page compatible with Antora, there are some rules to follow.
In particular, some AsciiDoc shortcuts or alternatives may not work.
On the other hand, Antora provides additional and specific attributes that can be utilized for maximum effect.

Some types of content require a specific structure.
These are listed and linked below and are described in their own separate pages.

NOTE: If you want to define a reusable content, consider using a xref:add-a-partial.adoc[Partial] instead.
See xref:pages-vs-partials.adoc[] for more information on the difference between those two.

== Result
An Antora and ASAM conforming page is created.

== Prerequisites
none

== How
IMPORTANT: These instructions already include the requirements of https://docs.antora.org/antora/2.1/page/create-standard-page/[Creating A Standard Page] by Antora implicitely.
However, if one deviates from this guide here, the Antora restrictions and requirements still apply!

. Find the module you want your page to be located in.
+
TIP: This should be the module which it relates to most closely.
See other pages in the modules in question for reference.
You can also look at the xref:content-structure.adoc[] for the Project Guide.

. Create your file in the "pages" folder or move it there
.. Alternatively, create a new folder and/or add your file to an existing folder within the "pages" folder if you want to add a structure within the module.
+
TIP: You can copy the corresponding template file from the examples folder in the project-guide module folder.

. Add the following standard content to your file and modify it accordingly:
+
[source,asciidoc]
----
include::example$reference-module-folder/pages/_template-default-page.adoc[]
----
+
NOTE: Remove the backslash in the template file before the include instruction when you copy the template file directly.
+
IMPORTANT: Some pages or all pages in a certain module may use a custom convention, such as displaying an icon.
Look at similar files/pages in the same module and follow those conventions, where they add to the template above.
