
:toc:
:imagesdir: ../images
:docker-download: https://docs.docker.com/get-docker/

= How To Use Docker For Asciidoctor

== Wait, What Is Docker?
// TODO

Docker is a tool for hosting and accessing so-called containers. For Asciidoc, docker can be used to run a pre-configured asciidoctor setup for creating html output locally. This removes the need to upload adoc files and use the build pipeline for every change you want to see.

If you do not have Docker installed, check out the <<../general_guidelines/Getting-Docker.adoc#,guide on getting docker>> before continuing.

== Setup

Setup oif docker and adding the docker-compose.yml to a project is described on the linked pages:

Tooling:: <<../general_guidelines/Getting-Docker.adoc#,Guide on getting docker>>

Project:: <<../tool-specific/StandardDockerConfig.adoc#,Standard docker-compose.yml>>

== Using Docker For Asciidoc

The <<../tool-specific/Recommended-VSCode-Extensions.adoc#AsciiDoc,VSCode extension for Asciidoc>> provides a decent preview. However, some styling and content will not look exactly as in the final result. If the layout and final look is important, you should create the HTMl output from the adoc files by using the asciidoctor docker container (configured in the <<../tool-specific/StandardDockerConfig.adoc#,standard docker-compose.yml>>).

For information on how to execute docker-compose, see the <<../tool-specific/DockerGuide.adoc#,Docker Guide>>.

After running docker-compose, one or more html files will have been created depending on your docker-compose.yml. If you use the standard configuration, the created file will be named "HTML_standard_local_build.html" and can be found in the same folder as your "docker-compose.yml" file.

TIP: For ensuring compliance with the ASAM style guidelines, make sure the project contains the relevant link:https://code.asam.net/common/style-resources[style resources] and that they are included as "preamble.adoc" in the file you are processing with asciidoctor.

== See Also
* link:../general_guidelines/Getting-Docker.adoc[Getting Docker]
* link:../tool-specific/DockerGuide.adoc[General Docker guide]
* link:../general_guidelines/WritingGuidelines.adoc[Writing guidelines]
* link:AsciiDoc-Guide.adoc[AsciiDoc guide]
* link:../tool-specific/StandardDockerConfig.adoc[Setup of standard docker-compose.yml]
