@startuml Models
package "UML Class Diagram"
{
    abstract OSC20
    interface PhysicalObject

    interface TrafficParticipant   
    entity Vehicle{}

	enum IntendedInfrastructure {
	driving
	sidewalk
	biking
    }

    class dynamicLimits{
        maxSpeed
        maxAcceleration
        maxDeceleration
}

OSC20 <|-- PhysicalObject
PhysicalObject <|-- TrafficParticipant
TrafficParticipant <|-- Vehicle
TrafficParticipant <|-- Person
TrafficParticipant <|-- Animal

'TrafficParticipant
TrafficParticipant -- IntendedInfrastructure
TrafficParticipant -- dynamicLimits

@enduml