= Developing The Idea
:description: Describes how an idea can be developed at ASAM.
:keywords: ideation, workshop

include::partial$_attributes.adoc[]
include::{abb}[]

When enough interest is raised (subject to suitable market relevance) but the idea requires more concept work before it can transition to the xref:proposal_phase.adoc[Proposal phase], ASAM will host an <<The Ideation Workshop,Ideation Workshop>> to further develop the topic.
If required, an ideation project is being set up that will meet regularly.

While the idea is being developed and fleshed out, the Idea Giver must gather enough project participants to be able to transition the idea to the proposal phase.


== The Ideation Workshop
[cols="1,5", grid = rows]
|===
h|Responsible
|{role-idea-giver}
h|Involved
| {role-member}, {role-gtm}

h| Step
| image:compendium:asam/ideation_phase-ideation_workshop.svg[]

h| TL;DR
| TODO
|===

xref:compendium:ASAM/phase-01_ideation/ideation_workshop_gameplan.adoc[]

TODO

== Ideation Projects

TODO

== Requirements For Transition To Proposal Phase
* The idea has been accepted by ASAM
* A first draft of the proposed idea has been set up ("Basis for Proposal")
* The minimum number of required participants has been reached or surpassed

[NOTE]
====
include::partial$minimum_required_participants_proposal.adoc[]
====


== What Happens Next?
Once all requirements are met (content and number of participants) and the idea is accepted by ASAM, the project transitions to the xref:getting-involved:proposal_phase.adoc[proposal phase].
The final goal is to transfer the idea into the regular xref:development_phase.adoc[Standard Development Process].