[[top-lists]]
= How to add lists in ASAM documents
:description: How-To for adding different types of lists in ASAM documents (standards).
:keywords: asciidoc,list,how-to
:reftext: Lists

== Bulleted lists
[cols="a,a"]
|===
|
....
* Item 1
* Item 2
** Item 2a
+
Continuation text for the previous list item.

* Item 3
....
|* Item 1

* Item 2
** Item 2a
+
Continuation text for the previous list item.

* Item 3
|===
TIP: The + is a list continuation.
It keeps the text inline with the list item.
Omitting the + affects the formatting of that line.

Adding another space before the + adopts the indentation of one level higher:

[cols="a,a"]
|===
|
....
* Item 1
* Item 2
** Item 2a

+
Continuation text for the previous list item.
* Item 3
....
|
* Item 1
* Item 2
** Item 2a

+
Continuation text for the previous list item.
* Item 3
|===

== Labeled lists

[cols="a,a"]
|===
|
....
Item 1::
Description 1

Item 2::
Description 2
....
|Item 1::
Description 1

Item 2::
Description 2

|

....
[horizontal]
Item 1::
Description 1

Item 2::
Description 2
....
|[horizontal]
Item 1::
Description 1

Item 2::
Description 2
|===

When you add [horizontal] above item 1, the label and description appear on the same line.
That works well when you have very short descriptions.


== Ordered lists


[cols="a,a"]
|===

|
....
. number
.. loweralpha
... lowerroman
. number
....
|
. number
.. loweralpha
... lowerroman
. number

|
We can mix ordered and bulleted lists however we want:

....
* bullet
. number
** bullet
.. loweralpha
....
|
* bullet
. number
** bullet
.. loweralpha

|===