name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  # pull_request:
  #   types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues with "Content feedback" name to project Project Guide Kanban
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: github.event.action == 'opened' && contains(github.event.issue.title, 'Content feedback')
      with:
        project: 'https://github.com/asam-ev/asam-project-guide/projects/1'

    - name: Assign issues with label "tooling" to Technical topics
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: contains(github.event.issue.labels.*.name, 'tooling')
      with:
        project: 'https://github.com/asam-ev/asam-project-guide/projects/2'

    - name: Assign issues with label "editorial guide" (or title including this) to Editorial guide
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: contains(github.event.issue.labels.*.name, 'editorial guide') || contains(github.event.issue.title, 'Editorial Guide')
      with:
        project: 'https://github.com/asam-ev/asam-project-guide/projects/3'

    # - name: Move issues with label "blocked" to blocked column
    #   uses: srggrs/assign-one-project-github-action@1.3.1
    #   if: contains(github.event.issue.labels.*.name, 'blocked')
    #   with:
    #     column_name: "Blocked"